using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MM.CoreModels
{
    public partial class CoreCity
    {


        public CoreCity()
        {
            CoreAddress = new HashSet<CoreAddress>();
        }
        public int Id { get; set; }
        public int? StateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        public virtual CoreState CoreState { get; set; }
        public virtual ICollection<CoreAddress> CoreAddress { get; set; }
    }

    public partial class CoreCityConfiguration : IEntityTypeConfiguration<CoreCity>
    {
        public void Configure(EntityTypeBuilder<CoreCity> builder)
        {
            builder.Property(e => e.CreatedOn).HasColumnType("datetime");

            builder.Property(e => e.ModifiedOn).HasColumnType("datetime");

            builder.Property(e => e.Name).HasMaxLength(100);

            builder.HasOne(d => d.CoreState)
                .WithMany(p => p.CoreCity)
                .HasForeignKey(d => d.StateId)
                .HasConstraintName("FK_CoreCity_State");
        }

    }
    public static partial class Seeder
    {
        public static void SeedCoreCity(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CoreCity>().HasData(
            new CoreCity { Id = 1, Name = "Adelaide", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 2, Name = "Alfred Nzo District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 3, Name = "Alice", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 4, Name = "Aliwal North", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 5, Name = "Amathole District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 6, Name = "Bhisho", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 7, Name = "Buffalo CoreCity Metropolitan Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 8, Name = "Burgersdorp", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 9, Name = "Butterworth", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 10, Name = "Cacadu District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 11, Name = "Chris Hani District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 12, Name = "Cradock", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 13, Name = "Dordrecht", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 14, Name = "East London", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 15, Name = "Elliot", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 16, Name = "Fort Beaufort", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 17, Name = "Graaff-Reinet", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 18, Name = "Grahamstown", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 19, Name = "Ilinge", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 20, Name = "Joe Gqabi District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 21, Name = "Kirkwood", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 22, Name = "Kruisfontein", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 23, Name = "Lady Frere", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 24, Name = "Middelburg", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 25, Name = "Molteno", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 26, Name = "Mthatha", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 27, Name = "Nelson Mandela Bay Metropolitan Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 28, Name = "OR Tambo District Municipality", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 29, Name = "Port Alfred", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 30, Name = "Port Elizabeth", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 31, Name = "Port Saint Johnâ€™s", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 32, Name = "Queensdale", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 33, Name = "Queenstown", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 34, Name = "Somerset East", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 35, Name = "Stutterheim", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 36, Name = "Uitenhage", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 37, Name = "Whittlesea", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 38, Name = "Willowmore", StateId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 39, Name = "Allanridge", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 40, Name = "Bethlehem", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 41, Name = "Bloemfontein", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 42, Name = "Bothaville", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 43, Name = "Botshabelo", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 44, Name = "Brandfort", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 45, Name = "Clocolan", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 46, Name = "Deneysville", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 47, Name = "Fezile Dabi District Municipality", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 48, Name = "Frankfort", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 49, Name = "Harrismith", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 50, Name = "Heilbron", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 51, Name = "Hennenman", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 52, Name = "Hoopstad", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 53, Name = "Koppies", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 54, Name = "Kroonstad", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 55, Name = "Kutloanong", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 56, Name = "Ladybrand", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 57, Name = "Lejweleputswa District Municipality", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 58, Name = "Lindley", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 59, Name = "Mangaung Metropolitan Municipality", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 60, Name = "Marquard", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 61, Name = "Parys", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 62, Name = "Phuthaditjhaba", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 63, Name = "Reitz", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 64, Name = "Sasolburg", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 65, Name = "Senekal", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 66, Name = "Thaba Nchu", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 67, Name = "Thabo Mofutsanyana District Municipality", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 68, Name = "Theunissen", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 69, Name = "Ventersburg", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 70, Name = "Viljoenskroon", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 71, Name = "Villiers", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 72, Name = "Virginia", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 73, Name = "Vrede", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 74, Name = "Vredefort", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 75, Name = "Welkom", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 76, Name = "Wesselsbron", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 77, Name = "Winburg", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 78, Name = "Xhariep District Municipality", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 79, Name = "Zastron", StateId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 80, Name = "Alberton", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 81, Name = "Benoni", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 82, Name = "Boksburg", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 83, Name = "Brakpan", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 84, Name = "Bronkhorstspruit", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 85, Name = "Carletonville", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 86, Name = "Centurion", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 87, Name = "CoreCity of Johannesburg Metropolitan Municipality", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 88, Name = "CoreCity of Tshwane Metropolitan Municipality", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 89, Name = "Cullinan", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 90, Name = "Diepsloot", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 91, Name = "Eastleigh", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 92, Name = "Eden Glen", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 93, Name = "Eden Glen Ext 60", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 94, Name = "Edenvale", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 95, Name = "Ekangala", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 96, Name = "Ekurhuleni Metropolitan Municipality", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 97, Name = "Heidelberg", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 98, Name = "Johannesburg", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 99, Name = "Krugersdorp", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 100, Name = "Mabopane", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 101, Name = "Midrand", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 102, Name = "Midstream", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 103, Name = "Modderfontein", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 104, Name = "Muldersdriseloop", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 105, Name = "Nigel", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 106, Name = "Orange Farm", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 107, Name = "Pretoria", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 108, Name = "Randburg", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 109, Name = "Randfontein", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 110, Name = "Roodepoort", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 111, Name = "Sedibeng District Municipality", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 112, Name = "Soweto", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 113, Name = "Springs", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 114, Name = "Tembisa", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 115, Name = "Vanderbijlpark", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 116, Name = "Vereeniging", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 117, Name = "West Rand District Municipality", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 118, Name = "Westonaria", StateId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 119, Name = "Amajuba District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 120, Name = "Ballito", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 121, Name = "Berea", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 122, Name = "Dundee", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 123, Name = "Durban", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 124, Name = "Ekuvukeni", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 125, Name = "eMkhomazi", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 126, Name = "Empangeni", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 127, Name = "Eshowe", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 128, Name = "eSikhaleni", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 129, Name = "eThekwini Metropolitan Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 130, Name = "Glencoe", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 131, Name = "Greytown", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 132, Name = "Hluhluwe", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 133, Name = "Howick", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 134, Name = "iLembe District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 135, Name = "Kokstad", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 136, Name = "KwaDukuza", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 137, Name = "Margate", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 138, Name = "Mondlo", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 139, Name = "Mooirivier", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 140, Name = "Mpophomeni", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 141, Name = "Mpumalanga", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 142, Name = "Mtubatuba", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 143, Name = "Ndwedwe", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 144, Name = "Newcastle", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 145, Name = "Pietermaritzburg", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 146, Name = "Port Shepstone", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 147, Name = "Richards Bay", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 148, Name = "Richmond", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 149, Name = "Scottburgh", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 150, Name = "Sisonke District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 151, Name = "Sundumbili", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 152, Name = "Ugu District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 153, Name = "Ulundi", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 154, Name = "uMgungundlovu District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 155, Name = "uMkhanyakude District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 156, Name = "uMzinyathi District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 157, Name = "uThukela District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 158, Name = "uThungulu District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 159, Name = "Utrecht", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 160, Name = "Vryheid", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 161, Name = "Zululand District Municipality", StateId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 162, Name = "Bochum", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 163, Name = "Capricorn District Municipality", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 164, Name = "Duiwelskloof", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 165, Name = "Ga-Kgapane", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 166, Name = "Giyani", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 167, Name = "Lebowakgomo", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 168, Name = "Louis Trichardt", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 169, Name = "Mankoeng", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 170, Name = "Modimolle", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 171, Name = "Mokopane", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 172, Name = "Mopani District Municipality", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 173, Name = "Musina", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 174, Name = "Nkowakowa", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 175, Name = "Phalaborwa", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 176, Name = "Polokwane", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 177, Name = "Sekhukhune District Municipality", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 178, Name = "Thabazimbi", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 179, Name = "Thohoyandou", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 180, Name = "Thulamahashi", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 181, Name = "Tzaneen", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 182, Name = "Vhembe District Municipality", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 183, Name = "Warmbaths", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 184, Name = "Waterberg District Municipality", StateId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 185, Name = "Balfour", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 186, Name = "Barberton", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 187, Name = "Belfast", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 188, Name = "Bethal", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 189, Name = "Breyten", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 190, Name = "Carolina", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 191, Name = "Delmas", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 192, Name = "Driefontein", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 193, Name = "Ehlanzeni District", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 194, Name = "eMbalenhle", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 195, Name = "Ermelo", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 196, Name = "Gert Sibande District Municipality", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 197, Name = "Hendrina", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 198, Name = "Komatipoort", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 199, Name = "Kriel", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 200, Name = "Lydenburg", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 201, Name = "Middelburg", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 202, Name = "Nelspruit", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 203, Name = "Nkangala District Municipality", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 204, Name = "Piet Retief", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 205, Name = "Secunda", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 206, Name = "Siyabuswa", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 207, Name = "Standerton", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 208, Name = "Volksrust", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 209, Name = "White River", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 210, Name = "Witbank", StateId = 6, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 211, Name = "Bloemhof", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 212, Name = "Bojanala Platinum District Municipality", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 213, Name = "Brits", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 214, Name = "Christiana", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 215, Name = "Dr Kenneth Kaunda District Municipality", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 216, Name = "Dr Ruth Segomotsi Mompati District Municipality", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 217, Name = "Fochville", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 218, Name = "Ga-Rankuwa", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 219, Name = "Jan Kempdorp", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 220, Name = "Klerksdorp", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 221, Name = "Koster", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 222, Name = "Lichtenburg", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 223, Name = "Mahikeng", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 224, Name = "Maile", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 225, Name = "Mmabatho", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 226, Name = "Ngaka Modiri Molema District Municipality", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 227, Name = "Orkney", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 228, Name = "Potchefstroom", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 229, Name = "Rustenburg", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 230, Name = "Schweizer-Reneke", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 231, Name = "Stilfontein", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 232, Name = "Vryburg", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 233, Name = "Wolmaransstad", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 234, Name = "Zeerust", StateId = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 235, Name = "Barkly West", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 236, Name = "Brandvlei", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 237, Name = "Calvinia", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 238, Name = "Carnarvon", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 239, Name = "Colesberg", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 240, Name = "DaniÃ«lskuil", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 241, Name = "De Aar", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 242, Name = "Frances Baard District Municipality", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 243, Name = "Fraserburg", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 244, Name = "John Taolo Gaetsewe District Municipality", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 245, Name = "Kathu", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 246, Name = "Kenhardt", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 247, Name = "Kimberley", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 248, Name = "Kuruman", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 249, Name = "Namakwa District Municipality", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 250, Name = "Noupoort", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 251, Name = "Orania", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 252, Name = "Pampierstad", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 253, Name = "Pixley ka Seme District Municipality", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 254, Name = "Pofadder", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 255, Name = "Postmasburg", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 256, Name = "Prieska", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 257, Name = "Ritchie", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 258, Name = "Siyanda District Municipality", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 259, Name = "Springbok", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 260, Name = "Upington", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 261, Name = "Van Wyksvlei", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 262, Name = "Warrenton", StateId = 8, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 263, Name = "Albertina", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 264, Name = "Arniston", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 265, Name = "Atlantis", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 266, Name = "Beaufort West", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 267, Name = "Bergvliet", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 268, Name = "Bredasdorp", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 269, Name = "Caledon", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 270, Name = "Calitzdorp", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 271, Name = "Cape Town", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 272, Name = "Cape Winelands District Municipality", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 273, Name = "Central Karoo District Municipality", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 274, Name = "Ceres", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 275, Name = "CoreCity of Cape Town", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 276, Name = "Clanwilliam", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 277, Name = "Claremont", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 278, Name = "Constantia", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 279, Name = "De Rust", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 280, Name = "Eden District Municipality", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 281, Name = "George", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 282, Name = "Grabouw", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 283, Name = "Hardys Memories of Africa", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 284, Name = "Hermanus", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 285, Name = "Knysna", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 286, Name = "Kraaifontein", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 287, Name = "Ladismith", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 288, Name = "Lansdowne", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 289, Name = "Malmesbury", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 290, Name = "Montagu", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 291, Name = "Moorreesburg", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 292, Name = "Mossel Bay", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 293, Name = "Newlands", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 294, Name = "Oudtshoorn", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 295, Name = "Overberg District Municipality", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 296, Name = "Paarl", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 297, Name = "Piketberg", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 298, Name = "Plettenberg Bay", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 299, Name = "Prince Albert", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 300, Name = "Retreat", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 301, Name = "Riversdale", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 302, Name = "Robertson", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 303, Name = "Rondebosch", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 304, Name = "Rosebank", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 305, Name = "Saldanha", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 306, Name = "Stellenbosch", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 307, Name = "Sunset Beach", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 308, Name = "Swellendam", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 309, Name = "Vredenburg", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 310, Name = "Vredendal", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 311, Name = "Wellington", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 312, Name = "West Coast District Municipality", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 313, Name = "Worcester", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
            new CoreCity { Id = 314, Name = "Zoar", StateId = 9, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now }
);
        }
    }
}
