using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MM.ClientModels
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            State = new HashSet<State>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<State> State { get; set; }
    }

    public partial class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.Property(e => e.Code).HasMaxLength(5);

            builder.Property(e => e.CreatedOn).HasColumnType("datetime");

            builder.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);

            builder.Property(e => e.ModifiedOn).HasColumnType("datetime");

            builder.Property(e => e.Name).HasMaxLength(100);
        }

    }
    public static partial class Seeder
    {
        public static void SeedCountry(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(

                    new Country { Id = 1, Code = "AF", Name = "Afghanistan", Description = "Afghanistan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 2, Code = "AL", Name = "Albania", Description = "Albania", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 3, Code = "DZ", Name = "Algeria", Description = "Algeria", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 4, Code = "AS", Name = "American Samoa", Description = "American Samoa", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 5, Code = "AD", Name = "Andorra", Description = "Andorra", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 6, Code = "AO", Name = "Angola", Description = "Angola", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 7, Code = "AI", Name = "Anguilla", Description = "Anguilla", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 8, Code = "AQ", Name = "Antarctica", Description = "Antarctica", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 9, Code = "AG", Name = "Antigua and Barbuda", Description = "Antigua and Barbuda", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 10, Code = "AR", Name = "Argentina", Description = "Argentina", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 11, Code = "AM", Name = "Armenia", Description = "Armenia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 12, Code = "AW", Name = "Aruba", Description = "Aruba", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 13, Code = "AU", Name = "Australia", Description = "Australia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 14, Code = "AT", Name = "Austria", Description = "Austria", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 15, Code = "AZ", Name = "Azerbaijan", Description = "Azerbaijan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 16, Code = "BS", Name = "Bahamas (the)", Description = "Bahamas (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 17, Code = "BH", Name = "Bahrain", Description = "Bahrain", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 18, Code = "BD", Name = "Bangladesh", Description = "Bangladesh", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 19, Code = "BB", Name = "Barbados", Description = "Barbados", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 20, Code = "BY", Name = "Belarus", Description = "Belarus", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 21, Code = "BE", Name = "Belgium", Description = "Belgium", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 22, Code = "BZ", Name = "Belize", Description = "Belize", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 23, Code = "BJ", Name = "Benin", Description = "Benin", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 24, Code = "BM", Name = "Bermuda", Description = "Bermuda", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 25, Code = "BT", Name = "Bhutan", Description = "Bhutan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 26, Code = "BO", Name = "Bolivia (Plurinational State of)", Description = "Bolivia (Plurinational State of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 27, Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba", Description = "Bonaire, Sint Eustatius and Saba", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 28, Code = "BA", Name = "Bosnia and Herzegovina", Description = "Bosnia and Herzegovina", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 29, Code = "BW", Name = "Botswana", Description = "Botswana", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 30, Code = "BV", Name = "Bouvet Island", Description = "Bouvet Island", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 31, Code = "BR", Name = "Brazil", Description = "Brazil", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 32, Code = "IO", Name = "British Indian Ocean Territory (the)", Description = "British Indian Ocean Territory (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 33, Code = "BN", Name = "Brunei Darussalam", Description = "Brunei Darussalam", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 34, Code = "BG", Name = "Bulgaria", Description = "Bulgaria", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 35, Code = "BF", Name = "Burkina Faso", Description = "Burkina Faso", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 36, Code = "BI", Name = "Burundi", Description = "Burundi", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 37, Code = "CV", Name = "Cabo Verde", Description = "Cabo Verde", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 38, Code = "KH", Name = "Cambodia", Description = "Cambodia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 39, Code = "CM", Name = "Cameroon", Description = "Cameroon", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 40, Code = "CA", Name = "Canada", Description = "Canada", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 41, Code = "KY", Name = "Cayman Islands (the)", Description = "Cayman Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 42, Code = "CF", Name = "Central African Republic (the)", Description = "Central African Republic (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 43, Code = "TD", Name = "Chad", Description = "Chad", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 44, Code = "CL", Name = "Chile", Description = "Chile", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 45, Code = "CN", Name = "China", Description = "China", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 46, Code = "CX", Name = "Christmas Island", Description = "Christmas Island", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 47, Code = "CC", Name = "Cocos (Keeling) Islands (the)", Description = "Cocos (Keeling) Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 48, Code = "CO", Name = "Colombia", Description = "Colombia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 49, Code = "KM", Name = "Comoros (the)", Description = "Comoros (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 50, Code = "CD", Name = "Congo (the Democratic Republic of the)", Description = "Congo (the Democratic Republic of the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 51, Code = "CG", Name = "Congo (the)", Description = "Congo (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 52, Code = "CK", Name = "Cook Islands (the)", Description = "Cook Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 53, Code = "CR", Name = "Costa Rica", Description = "Costa Rica", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 54, Code = "HR", Name = "Croatia", Description = "Croatia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 55, Code = "CU", Name = "Cuba", Description = "Cuba", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 56, Code = "CW", Name = "Curaçao", Description = "Curaçao", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 57, Code = "CY", Name = "Cyprus", Description = "Cyprus", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 58, Code = "CZ", Name = "Czechia", Description = "Czechia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 59, Code = "CI", Name = "Côte d'Ivoire", Description = "Côte d'Ivoire", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 60, Code = "DK", Name = "Denmark", Description = "Denmark", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 61, Code = "DJ", Name = "Djibouti", Description = "Djibouti", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 62, Code = "DM", Name = "Dominica", Description = "Dominica", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 63, Code = "DO", Name = "Dominican Republic (the)", Description = "Dominican Republic (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 64, Code = "EC", Name = "Ecuador", Description = "Ecuador", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 65, Code = "EG", Name = "Egypt", Description = "Egypt", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 66, Code = "SV", Name = "El Salvador", Description = "El Salvador", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 67, Code = "GQ", Name = "Equatorial Guinea", Description = "Equatorial Guinea", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 68, Code = "ER", Name = "Eritrea", Description = "Eritrea", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 69, Code = "EE", Name = "Estonia", Description = "Estonia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 70, Code = "SZ", Name = "Eswatini", Description = "Eswatini", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 71, Code = "ET", Name = "Ethiopia", Description = "Ethiopia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 72, Code = "FK", Name = "Falkland Islands (the) [Malvinas]", Description = "Falkland Islands (the) [Malvinas]", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 73, Code = "FO", Name = "Faroe Islands (the)", Description = "Faroe Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 74, Code = "FJ", Name = "Fiji", Description = "Fiji", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 75, Code = "FI", Name = "Finland", Description = "Finland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 76, Code = "FR", Name = "France", Description = "France", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 77, Code = "GF", Name = "French Guiana", Description = "French Guiana", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 78, Code = "PF", Name = "French Polynesia", Description = "French Polynesia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 79, Code = "TF", Name = "French Southern Territories (the)", Description = "French Southern Territories (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 80, Code = "GA", Name = "Gabon", Description = "Gabon", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 81, Code = "GM", Name = "Gambia (the)", Description = "Gambia (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 82, Code = "GE", Name = "Georgia", Description = "Georgia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 83, Code = "DE", Name = "Germany", Description = "Germany", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 84, Code = "GH", Name = "Ghana", Description = "Ghana", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 85, Code = "GI", Name = "Gibraltar", Description = "Gibraltar", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 86, Code = "GR", Name = "Greece", Description = "Greece", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 87, Code = "GL", Name = "Greenland", Description = "Greenland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 88, Code = "GD", Name = "Grenada", Description = "Grenada", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 89, Code = "GP", Name = "Guadeloupe", Description = "Guadeloupe", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 90, Code = "GU", Name = "Guam", Description = "Guam", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 91, Code = "GT", Name = "Guatemala", Description = "Guatemala", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 92, Code = "GG", Name = "Guernsey", Description = "Guernsey", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 93, Code = "GN", Name = "Guinea", Description = "Guinea", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 94, Code = "GW", Name = "Guinea-Bissau", Description = "Guinea-Bissau", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 95, Code = "GY", Name = "Guyana", Description = "Guyana", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 96, Code = "HT", Name = "Haiti", Description = "Haiti", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 97, Code = "HM", Name = "Heard Island and McDonald Islands", Description = "Heard Island and McDonald Islands", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 98, Code = "VA", Name = "Holy See (the)", Description = "Holy See (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 99, Code = "HN", Name = "Honduras", Description = "Honduras", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 100, Code = "HK", Name = "Hong Kong", Description = "Hong Kong", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 101, Code = "HU", Name = "Hungary", Description = "Hungary", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 102, Code = "IS", Name = "Iceland", Description = "Iceland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 103, Code = "IN", Name = "India", Description = "India", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 104, Code = "ID", Name = "Indonesia", Description = "Indonesia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 105, Code = "IR", Name = "Iran (Islamic Republic of)", Description = "Iran (Islamic Republic of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 106, Code = "IQ", Name = "Iraq", Description = "Iraq", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 107, Code = "IE", Name = "Ireland", Description = "Ireland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 108, Code = "IM", Name = "Isle of Man", Description = "Isle of Man", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 109, Code = "IL", Name = "Israel", Description = "Israel", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 110, Code = "IT", Name = "Italy", Description = "Italy", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 111, Code = "JM", Name = "Jamaica", Description = "Jamaica", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 112, Code = "JP", Name = "Japan", Description = "Japan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 113, Code = "JE", Name = "Jersey", Description = "Jersey", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 114, Code = "JO", Name = "Jordan", Description = "Jordan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 115, Code = "KZ", Name = "Kazakhstan", Description = "Kazakhstan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 116, Code = "KE", Name = "Kenya", Description = "Kenya", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 117, Code = "KI", Name = "Kiribati", Description = "Kiribati", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 118, Code = "KP", Name = "Korea (the Democratic People's Republic of)", Description = "Korea (the Democratic People's Republic of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 119, Code = "KR", Name = "Korea (the Republic of)", Description = "Korea (the Republic of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 120, Code = "KW", Name = "Kuwait", Description = "Kuwait", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 121, Code = "KG", Name = "Kyrgyzstan", Description = "Kyrgyzstan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 122, Code = "LA", Name = "Lao People's Democratic Republic (the)", Description = "Lao People's Democratic Republic (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 123, Code = "LV", Name = "Latvia", Description = "Latvia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 124, Code = "LB", Name = "Lebanon", Description = "Lebanon", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 125, Code = "LS", Name = "Lesotho", Description = "Lesotho", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 126, Code = "LR", Name = "Liberia", Description = "Liberia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 127, Code = "LY", Name = "Libya", Description = "Libya", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 128, Code = "LI", Name = "Liechtenstein", Description = "Liechtenstein", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 129, Code = "LT", Name = "Lithuania", Description = "Lithuania", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 130, Code = "LU", Name = "Luxembourg", Description = "Luxembourg", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 131, Code = "MO", Name = "Macao", Description = "Macao", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 132, Code = "MG", Name = "Madagascar", Description = "Madagascar", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 133, Code = "MW", Name = "Malawi", Description = "Malawi", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 134, Code = "MY", Name = "Malaysia", Description = "Malaysia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 135, Code = "MV", Name = "Maldives", Description = "Maldives", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 136, Code = "ML", Name = "Mali", Description = "Mali", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 137, Code = "MT", Name = "Malta", Description = "Malta", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 138, Code = "MH", Name = "Marshall Islands (the)", Description = "Marshall Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 139, Code = "MQ", Name = "Martinique", Description = "Martinique", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 140, Code = "MR", Name = "Mauritania", Description = "Mauritania", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 141, Code = "MU", Name = "Mauritius", Description = "Mauritius", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 142, Code = "YT", Name = "Mayotte", Description = "Mayotte", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 143, Code = "MX", Name = "Mexico", Description = "Mexico", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 144, Code = "FM", Name = "Micronesia (Federated States of)", Description = "Micronesia (Federated States of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 145, Code = "MD", Name = "Moldova (the Republic of)", Description = "Moldova (the Republic of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 146, Code = "MC", Name = "Monaco", Description = "Monaco", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 147, Code = "MN", Name = "Mongolia", Description = "Mongolia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 148, Code = "ME", Name = "Montenegro", Description = "Montenegro", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 149, Code = "MS", Name = "Montserrat", Description = "Montserrat", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 150, Code = "MA", Name = "Morocco", Description = "Morocco", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 151, Code = "MZ", Name = "Mozambique", Description = "Mozambique", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 152, Code = "MM", Name = "Myanmar", Description = "Myanmar", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 153, Code = "NA", Name = "Namibia", Description = "Namibia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 154, Code = "NR", Name = "Nauru", Description = "Nauru", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 155, Code = "NP", Name = "Nepal", Description = "Nepal", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 156, Code = "NL", Name = "Netherlands (the)", Description = "Netherlands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 157, Code = "NC", Name = "New Caledonia", Description = "New Caledonia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 158, Code = "NZ", Name = "New Zealand", Description = "New Zealand", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 159, Code = "NI", Name = "Nicaragua", Description = "Nicaragua", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 160, Code = "NE", Name = "Niger (the)", Description = "Niger (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 161, Code = "NG", Name = "Nigeria", Description = "Nigeria", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 162, Code = "NU", Name = "Niue", Description = "Niue", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 163, Code = "NF", Name = "Norfolk Island", Description = "Norfolk Island", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 164, Code = "MP", Name = "Northern Mariana Islands (the)", Description = "Northern Mariana Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 165, Code = "NO", Name = "Norway", Description = "Norway", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 166, Code = "OM", Name = "Oman", Description = "Oman", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 167, Code = "PK", Name = "Pakistan", Description = "Pakistan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 168, Code = "PW", Name = "Palau", Description = "Palau", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 169, Code = "PS", Name = "Palestine, State of", Description = "Palestine, State of", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 170, Code = "PA", Name = "Panama", Description = "Panama", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 171, Code = "PG", Name = "Papua New Guinea", Description = "Papua New Guinea", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 172, Code = "PY", Name = "Paraguay", Description = "Paraguay", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 173, Code = "PE", Name = "Peru", Description = "Peru", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 174, Code = "PH", Name = "Philippines (the)", Description = "Philippines (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 175, Code = "PN", Name = "Pitcairn", Description = "Pitcairn", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 176, Code = "PL", Name = "Poland", Description = "Poland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 177, Code = "PT", Name = "Portugal", Description = "Portugal", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 178, Code = "PR", Name = "Puerto Rico", Description = "Puerto Rico", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 179, Code = "QA", Name = "Qatar", Description = "Qatar", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 180, Code = "MK", Name = "Republic of North Macedonia", Description = "Republic of North Macedonia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 181, Code = "RO", Name = "Romania", Description = "Romania", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 182, Code = "RU", Name = "Russian Federation (the)", Description = "Russian Federation (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 183, Code = "RW", Name = "Rwanda", Description = "Rwanda", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 184, Code = "RE", Name = "Réunion", Description = "Réunion", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 185, Code = "BL", Name = "Saint Barthélemy", Description = "Saint Barthélemy", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 186, Code = "SH", Name = "Saint Helena, Ascension and Tristan da Cunha", Description = "Saint Helena, Ascension and Tristan da Cunha", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 187, Code = "KN", Name = "Saint Kitts and Nevis", Description = "Saint Kitts and Nevis", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 188, Code = "LC", Name = "Saint Lucia", Description = "Saint Lucia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 189, Code = "MF", Name = "Saint Martin (French part)", Description = "Saint Martin (French part)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 190, Code = "PM", Name = "Saint Pierre and Miquelon", Description = "Saint Pierre and Miquelon", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 191, Code = "VC", Name = "Saint Vincent and the Grenadines", Description = "Saint Vincent and the Grenadines", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 192, Code = "WS", Name = "Samoa", Description = "Samoa", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 193, Code = "SM", Name = "San Marino", Description = "San Marino", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 194, Code = "ST", Name = "Sao Tome and Principe", Description = "Sao Tome and Principe", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 195, Code = "SA", Name = "Saudi Arabia", Description = "Saudi Arabia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 196, Code = "SN", Name = "Senegal", Description = "Senegal", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 197, Code = "RS", Name = "Serbia", Description = "Serbia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 198, Code = "SC", Name = "Seychelles", Description = "Seychelles", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 199, Code = "SL", Name = "Sierra Leone", Description = "Sierra Leone", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 200, Code = "SG", Name = "Singapore", Description = "Singapore", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 201, Code = "SX", Name = "Sint Maarten (Dutch part)", Description = "Sint Maarten (Dutch part)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 202, Code = "SK", Name = "Slovakia", Description = "Slovakia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 203, Code = "SI", Name = "Slovenia", Description = "Slovenia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 204, Code = "SB", Name = "Solomon Islands", Description = "Solomon Islands", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 205, Code = "SO", Name = "Somalia", Description = "Somalia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 206, Code = "ZA", Name = "South Africa", Description = "South Africa", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 207, Code = "GS", Name = "South Georgia and the South Sandwich Islands", Description = "South Georgia and the South Sandwich Islands", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 208, Code = "SS", Name = "South Sudan", Description = "South Sudan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 209, Code = "ES", Name = "Spain", Description = "Spain", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 210, Code = "LK", Name = "Sri Lanka", Description = "Sri Lanka", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 211, Code = "SD", Name = "Sudan (the)", Description = "Sudan (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 212, Code = "SR", Name = "Suriname", Description = "Suriname", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 213, Code = "SJ", Name = "Svalbard and Jan Mayen", Description = "Svalbard and Jan Mayen", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 214, Code = "SE", Name = "Sweden", Description = "Sweden", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 215, Code = "CH", Name = "Switzerland", Description = "Switzerland", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 216, Code = "SY", Name = "Syrian Arab Republic", Description = "Syrian Arab Republic", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 217, Code = "TW", Name = "Taiwan (Province of China)", Description = "Taiwan (Province of China)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 218, Code = "TJ", Name = "Tajikistan", Description = "Tajikistan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 219, Code = "TZ", Name = "Tanzania, United Republic of", Description = "Tanzania, United Republic of", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 220, Code = "TH", Name = "Thailand", Description = "Thailand", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 221, Code = "TL", Name = "Timor-Leste", Description = "Timor-Leste", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 222, Code = "TG", Name = "Togo", Description = "Togo", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 223, Code = "TK", Name = "Tokelau", Description = "Tokelau", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 224, Code = "TO", Name = "Tonga", Description = "Tonga", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 225, Code = "TT", Name = "Trinidad and Tobago", Description = "Trinidad and Tobago", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 226, Code = "TN", Name = "Tunisia", Description = "Tunisia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 227, Code = "TR", Name = "Turkey", Description = "Turkey", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 228, Code = "TM", Name = "Turkmenistan", Description = "Turkmenistan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 229, Code = "TC", Name = "Turks and Caicos Islands (the)", Description = "Turks and Caicos Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 230, Code = "TV", Name = "Tuvalu", Description = "Tuvalu", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 231, Code = "UG", Name = "Uganda", Description = "Uganda", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 232, Code = "UA", Name = "Ukraine", Description = "Ukraine", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 233, Code = "AE", Name = "United Arab Emirates (the)", Description = "United Arab Emirates (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 234, Code = "GB", Name = "United Kingdom of Great Britain and Northern Ireland (the)", Description = "United Kingdom of Great Britain and Northern Ireland (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 235, Code = "UM", Name = "United States Minor Outlying Islands (the)", Description = "United States Minor Outlying Islands (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 236, Code = "US", Name = "United States of America (the)", Description = "United States of America (the)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 237, Code = "UY", Name = "Uruguay", Description = "Uruguay", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 238, Code = "UZ", Name = "Uzbekistan", Description = "Uzbekistan", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 239, Code = "VU", Name = "Vanuatu", Description = "Vanuatu", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 240, Code = "VE", Name = "Venezuela (Bolivarian Republic of)", Description = "Venezuela (Bolivarian Republic of)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 241, Code = "VN", Name = "Viet Nam", Description = "Viet Nam", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 242, Code = "VG", Name = "Virgin Islands (British)", Description = "Virgin Islands (British)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 243, Code = "VI", Name = "Virgin Islands (U.S.)", Description = "Virgin Islands (U.S.)", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 244, Code = "WF", Name = "Wallis and Futuna", Description = "Wallis and Futuna", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 245, Code = "EH", Name = "Western Sahara", Description = "Western Sahara", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 246, Code = "YE", Name = "Yemen", Description = "Yemen", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 247, Code = "ZM", Name = "Zambia", Description = "Zambia", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 248, Code = "ZW", Name = "Zimbabwe", Description = "Zimbabwe", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 249, Code = "AX", Name = "Åland Islands", Description = "Åland Islands", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
                    new Country { Id = 250, Code = "SZ", Name = "SWAZILAND", Description = "SWAZILAND", CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now }

             );
        }
    }
}

