using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MM.ClientModels
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            State = new HashSet<State>();
        }

        public int Id { get; set; }
        public string ISO2Code { get; set; }
        public string ISO3Code { get; set; }
        public int? PhoneCode { get; set; }
        public string CountryCode { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<State> State { get; set; }
    }

    public partial class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.Property(e => e.ISO2Code).HasMaxLength(2);
            builder.Property(e => e.ISO3Code).HasMaxLength(3);


            builder.Property(e => e.CreatedOn).HasColumnType("datetime");
            builder.Property(e => e.ModifiedOn).HasColumnType("datetime");
            builder.Property(e => e.Name).HasMaxLength(100);
            builder.Property(e => e.CountryCode).IsRequired(false).HasMaxLength(3);
        }

    }
    public static partial class Seeder
    {
        public static void SeedCountry(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(

                new Country { Id = 1, ISO2Code = "AF", ISO3Code = "AFG", Name = "Afghanistan", CountryCode = "AFN", PhoneCode = 93, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 2, ISO2Code = "AX", ISO3Code = "ALA", Name = "Aland Islands", CountryCode = "EUR", PhoneCode = 340, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 3, ISO2Code = "AL", ISO3Code = "ALB", Name = "Albania", CountryCode = "ALL", PhoneCode = 355, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 4, ISO2Code = "DZ", ISO3Code = "DZA", Name = "Algeria", CountryCode = "DZD", PhoneCode = 213, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 5, ISO2Code = "AS", ISO3Code = "ASM", Name = "American Samoa", CountryCode = "USD", PhoneCode = -683, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 6, ISO2Code = "AD", ISO3Code = "AND", Name = "Andorra", CountryCode = "EUR", PhoneCode = 376, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 7, ISO2Code = "AO", ISO3Code = "AGO", Name = "Angola", CountryCode = "AOA", PhoneCode = 244, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 8, ISO2Code = "AI", ISO3Code = "AIA", Name = "Anguilla", CountryCode = "XCD", PhoneCode = -263, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 9, ISO2Code = "AQ", ISO3Code = "ATA", Name = "Antarctica", CountryCode = null, PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 10, ISO2Code = "AG", ISO3Code = "ATG", Name = "Antigua And Barbuda", CountryCode = "XCD", PhoneCode = -267, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 11, ISO2Code = "AR", ISO3Code = "ARG", Name = "Argentina", CountryCode = "ARS", PhoneCode = 54, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 12, ISO2Code = "AM", ISO3Code = "ARM", Name = "Armenia", CountryCode = "AMD", PhoneCode = 374, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 13, ISO2Code = "AW", ISO3Code = "ABW", Name = "Aruba", CountryCode = "AWG", PhoneCode = 297, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 14, ISO2Code = "AU", ISO3Code = "AUS", Name = "Australia", CountryCode = "AUD", PhoneCode = 61, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 15, ISO2Code = "AT", ISO3Code = "AUT", Name = "Austria", CountryCode = "EUR", PhoneCode = 43, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 16, ISO2Code = "AZ", ISO3Code = "AZE", Name = "Azerbaijan", CountryCode = "AZN", PhoneCode = 994, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 17, ISO2Code = "BS", ISO3Code = "BHS", Name = "Bahamas The", CountryCode = "BSD", PhoneCode = -241, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 18, ISO2Code = "BH", ISO3Code = "BHR", Name = "Bahrain", CountryCode = "BHD", PhoneCode = 973, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 19, ISO2Code = "BD", ISO3Code = "BGD", Name = "Bangladesh", CountryCode = "BDT", PhoneCode = 880, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 20, ISO2Code = "BB", ISO3Code = "BRB", Name = "Barbados", CountryCode = "BBD", PhoneCode = -245, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 21, ISO2Code = "BY", ISO3Code = "BLR", Name = "Belarus", CountryCode = "BYR", PhoneCode = 375, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 22, ISO2Code = "BE", ISO3Code = "BEL", Name = "Belgium", CountryCode = "EUR", PhoneCode = 32, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 23, ISO2Code = "BZ", ISO3Code = "BLZ", Name = "Belize", CountryCode = "BZD", PhoneCode = 501, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 24, ISO2Code = "BJ", ISO3Code = "BEN", Name = "Benin", CountryCode = "XOF", PhoneCode = 229, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 25, ISO2Code = "BM", ISO3Code = "BMU", Name = "Bermuda", CountryCode = "BMD", PhoneCode = -440, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 26, ISO2Code = "BT", ISO3Code = "BTN", Name = "Bhutan", CountryCode = "BTN", PhoneCode = 975, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 27, ISO2Code = "BO", ISO3Code = "BOL", Name = "Bolivia", CountryCode = "BOB", PhoneCode = 591, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 28, ISO2Code = "BA", ISO3Code = "BIH", Name = "Bosnia and Herzegovina", CountryCode = "BAM", PhoneCode = 387, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 29, ISO2Code = "BW", ISO3Code = "BWA", Name = "Botswana", CountryCode = "BWP", PhoneCode = 267, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 30, ISO2Code = "BV", ISO3Code = "BVT", Name = "Bouvet Island", CountryCode = "NOK", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 31, ISO2Code = "BR", ISO3Code = "BRA", Name = "Brazil", CountryCode = "BRL", PhoneCode = 55, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 32, ISO2Code = "IO", ISO3Code = "IOT", Name = "British Indian Ocean Territory", CountryCode = "USD", PhoneCode = 246, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 33, ISO2Code = "BN", ISO3Code = "BRN", Name = "Brunei", CountryCode = "BND", PhoneCode = 673, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 34, ISO2Code = "BG", ISO3Code = "BGR", Name = "Bulgaria", CountryCode = "BGN", PhoneCode = 359, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 35, ISO2Code = "BF", ISO3Code = "BFA", Name = "Burkina Faso", CountryCode = "XOF", PhoneCode = 226, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 36, ISO2Code = "BI", ISO3Code = "BDI", Name = "Burundi", CountryCode = "BIF", PhoneCode = 257, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 37, ISO2Code = "KH", ISO3Code = "KHM", Name = "Cambodia", CountryCode = "KHR", PhoneCode = 855, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 38, ISO2Code = "CM", ISO3Code = "CMR", Name = "Cameroon", CountryCode = "XAF", PhoneCode = 237, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 39, ISO2Code = "CA", ISO3Code = "CAN", Name = "Canada", CountryCode = "CAD", PhoneCode = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 40, ISO2Code = "CV", ISO3Code = "CPV", Name = "Cape Verde", CountryCode = "CVE", PhoneCode = 238, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 41, ISO2Code = "KY", ISO3Code = "CYM", Name = "Cayman Islands", CountryCode = "KYD", PhoneCode = -344, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 42, ISO2Code = "CF", ISO3Code = "CAF", Name = "Central African Republic", CountryCode = "XAF", PhoneCode = 236, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 43, ISO2Code = "TD", ISO3Code = "TCD", Name = "Chad", CountryCode = "XAF", PhoneCode = 235, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 44, ISO2Code = "CL", ISO3Code = "CHL", Name = "Chile", CountryCode = "CLP", PhoneCode = 56, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 45, ISO2Code = "CN", ISO3Code = "CHN", Name = "China", CountryCode = "CNY", PhoneCode = 86, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 46, ISO2Code = "CX", ISO3Code = "CXR", Name = "Christmas Island", CountryCode = "AUD", PhoneCode = 61, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 47, ISO2Code = "CC", ISO3Code = "CCK", Name = "Cocos (Keeling) Islands", CountryCode = "AUD", PhoneCode = 61, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 48, ISO2Code = "CO", ISO3Code = "COL", Name = "Colombia", CountryCode = "COP", PhoneCode = 57, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 49, ISO2Code = "KM", ISO3Code = "COM", Name = "Comoros", CountryCode = "KMF", PhoneCode = 269, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 50, ISO2Code = "CG", ISO3Code = "COG", Name = "Congo", CountryCode = "XAF", PhoneCode = 242, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 51, ISO2Code = "CD", ISO3Code = "COD", Name = "Congo The Democratic Republic Of The", CountryCode = "CDF", PhoneCode = 243, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 52, ISO2Code = "CK", ISO3Code = "COK", Name = "Cook Islands", CountryCode = "NZD", PhoneCode = 682, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 53, ISO2Code = "CR", ISO3Code = "CRI", Name = "Costa Rica", CountryCode = "CRC", PhoneCode = 506, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 54, ISO2Code = "CI", ISO3Code = "CIV", Name = "Cote D'Ivoire (Ivory Coast)", CountryCode = "XOF", PhoneCode = 225, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 55, ISO2Code = "HR", ISO3Code = "HRV", Name = "Croatia (Hrvatska)", CountryCode = "HRK", PhoneCode = 385, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 56, ISO2Code = "CU", ISO3Code = "CUB", Name = "Cuba", CountryCode = "CUP", PhoneCode = 53, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 57, ISO2Code = "CY", ISO3Code = "CYP", Name = "Cyprus", CountryCode = "EUR", PhoneCode = 357, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 58, ISO2Code = "CZ", ISO3Code = "CZE", Name = "Czech Republic", CountryCode = "CZK", PhoneCode = 420, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 59, ISO2Code = "DK", ISO3Code = "DNK", Name = "Denmark", CountryCode = "DKK", PhoneCode = 45, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 60, ISO2Code = "DJ", ISO3Code = "DJI", Name = "Djibouti", CountryCode = "DJF", PhoneCode = 253, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 61, ISO2Code = "DM", ISO3Code = "DMA", Name = "Dominica", CountryCode = "XCD", PhoneCode = -766, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 62, ISO2Code = "DO", ISO3Code = "DOM", Name = "Dominican Republic", CountryCode = "DOP", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 63, ISO2Code = "TL", ISO3Code = "TLS", Name = "East Timor", CountryCode = "USD", PhoneCode = 670, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 64, ISO2Code = "EC", ISO3Code = "ECU", Name = "Ecuador", CountryCode = "USD", PhoneCode = 593, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 65, ISO2Code = "EG", ISO3Code = "EGY", Name = "Egypt", CountryCode = "EGP", PhoneCode = 20, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 66, ISO2Code = "SV", ISO3Code = "SLV", Name = "El Salvador", CountryCode = "USD", PhoneCode = 503, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 67, ISO2Code = "GQ", ISO3Code = "GNQ", Name = "Equatorial Guinea", CountryCode = "XAF", PhoneCode = 240, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 68, ISO2Code = "ER", ISO3Code = "ERI", Name = "Eritrea", CountryCode = "ERN", PhoneCode = 291, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 69, ISO2Code = "EE", ISO3Code = "EST", Name = "Estonia", CountryCode = "EUR", PhoneCode = 372, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 70, ISO2Code = "ET", ISO3Code = "ETH", Name = "Ethiopia", CountryCode = "ETB", PhoneCode = 251, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 71, ISO2Code = "FK", ISO3Code = "FLK", Name = "Falkland Islands", CountryCode = "FKP", PhoneCode = 500, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 72, ISO2Code = "FO", ISO3Code = "FRO", Name = "Faroe Islands", CountryCode = "DKK", PhoneCode = 298, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 73, ISO2Code = "FJ", ISO3Code = "FJI", Name = "Fiji Islands", CountryCode = "FJD", PhoneCode = 679, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 74, ISO2Code = "FI", ISO3Code = "FIN", Name = "Finland", CountryCode = "EUR", PhoneCode = 358, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 75, ISO2Code = "FR", ISO3Code = "FRA", Name = "France", CountryCode = "EUR", PhoneCode = 33, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 76, ISO2Code = "GF", ISO3Code = "GUF", Name = "French Guiana", CountryCode = "EUR", PhoneCode = 594, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 77, ISO2Code = "PF", ISO3Code = "PYF", Name = "French Polynesia", CountryCode = "XPF", PhoneCode = 689, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 78, ISO2Code = "TF", ISO3Code = "ATF", Name = "French Southern Territories", CountryCode = "EUR", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 79, ISO2Code = "GA", ISO3Code = "GAB", Name = "Gabon", CountryCode = "XAF", PhoneCode = 241, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 80, ISO2Code = "GM", ISO3Code = "GMB", Name = "Gambia The", CountryCode = "GMD", PhoneCode = 220, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 81, ISO2Code = "GE", ISO3Code = "GEO", Name = "Georgia", CountryCode = "GEL", PhoneCode = 995, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 82, ISO2Code = "DE", ISO3Code = "DEU", Name = "Germany", CountryCode = "EUR", PhoneCode = 49, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 83, ISO2Code = "GH", ISO3Code = "GHA", Name = "Ghana", CountryCode = "GHS", PhoneCode = 233, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 84, ISO2Code = "GI", ISO3Code = "GIB", Name = "Gibraltar", CountryCode = "GIP", PhoneCode = 350, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 85, ISO2Code = "GR", ISO3Code = "GRC", Name = "Greece", CountryCode = "EUR", PhoneCode = 30, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 86, ISO2Code = "GL", ISO3Code = "GRL", Name = "Greenland", CountryCode = "DKK", PhoneCode = 299, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 87, ISO2Code = "GD", ISO3Code = "GRD", Name = "Grenada", CountryCode = "XCD", PhoneCode = -472, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 88, ISO2Code = "GP", ISO3Code = "GLP", Name = "Guadeloupe", CountryCode = "EUR", PhoneCode = 590, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 89, ISO2Code = "GU", ISO3Code = "GUM", Name = "Guam", CountryCode = "USD", PhoneCode = -670, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 90, ISO2Code = "GT", ISO3Code = "GTM", Name = "Guatemala", CountryCode = "GTQ", PhoneCode = 502, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 91, ISO2Code = "GG", ISO3Code = "GGY", Name = "Guernsey and Alderney", CountryCode = "GBP", PhoneCode = -1437, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 92, ISO2Code = "GN", ISO3Code = "GIN", Name = "Guinea", CountryCode = "GNF", PhoneCode = 224, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 93, ISO2Code = "GW", ISO3Code = "GNB", Name = "Guinea-Bissau", CountryCode = "XOF", PhoneCode = 245, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 94, ISO2Code = "GY", ISO3Code = "GUY", Name = "Guyana", CountryCode = "GYD", PhoneCode = 592, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 95, ISO2Code = "HT", ISO3Code = "HTI", Name = "Haiti", CountryCode = "HTG", PhoneCode = 509, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 96, ISO2Code = "HM", ISO3Code = "HMD", Name = "Heard and McDonald Islands", CountryCode = "AUD", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 97, ISO2Code = "HN", ISO3Code = "HND", Name = "Honduras", CountryCode = "HNL", PhoneCode = 504, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 98, ISO2Code = "HK", ISO3Code = "HKG", Name = "Hong Kong S.A.R.", CountryCode = "HKD", PhoneCode = 852, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 99, ISO2Code = "HU", ISO3Code = "HUN", Name = "Hungary", CountryCode = "HUF", PhoneCode = 36, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 100, ISO2Code = "IS", ISO3Code = "ISL", Name = "Iceland", CountryCode = "ISK", PhoneCode = 354, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 101, ISO2Code = "IN", ISO3Code = "IND", Name = "India", CountryCode = "INR", PhoneCode = 91, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 102, ISO2Code = "ID", ISO3Code = "IDN", Name = "Indonesia", CountryCode = "IDR", PhoneCode = 62, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 103, ISO2Code = "IR", ISO3Code = "IRN", Name = "Iran", CountryCode = "IRR", PhoneCode = 98, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 104, ISO2Code = "IQ", ISO3Code = "IRQ", Name = "Iraq", CountryCode = "IQD", PhoneCode = 964, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 105, ISO2Code = "IE", ISO3Code = "IRL", Name = "Ireland", CountryCode = "EUR", PhoneCode = 353, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 106, ISO2Code = "IL", ISO3Code = "ISR", Name = "Israel", CountryCode = "ILS", PhoneCode = 972, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 107, ISO2Code = "IT", ISO3Code = "ITA", Name = "Italy", CountryCode = "EUR", PhoneCode = 39, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 108, ISO2Code = "JM", ISO3Code = "JAM", Name = "Jamaica", CountryCode = "JMD", PhoneCode = -875, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 109, ISO2Code = "JP", ISO3Code = "JPN", Name = "Japan", CountryCode = "JPY", PhoneCode = 81, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 110, ISO2Code = "JE", ISO3Code = "JEY", Name = "Jersey", CountryCode = "GBP", PhoneCode = -1490, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 111, ISO2Code = "JO", ISO3Code = "JOR", Name = "Jordan", CountryCode = "JOD", PhoneCode = 962, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 112, ISO2Code = "KZ", ISO3Code = "KAZ", Name = "Kazakhstan", CountryCode = "KZT", PhoneCode = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 113, ISO2Code = "KE", ISO3Code = "KEN", Name = "Kenya", CountryCode = "KES", PhoneCode = 254, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 114, ISO2Code = "KI", ISO3Code = "KIR", Name = "Kiribati", CountryCode = "AUD", PhoneCode = 686, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 115, ISO2Code = "KP", ISO3Code = "PRK", Name = "Korea North", CountryCode = "KPW", PhoneCode = 850, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 116, ISO2Code = "KR", ISO3Code = "KOR", Name = "Korea South", CountryCode = "KRW", PhoneCode = 82, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 117, ISO2Code = "KW", ISO3Code = "KWT", Name = "Kuwait", CountryCode = "KWD", PhoneCode = 965, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 118, ISO2Code = "KG", ISO3Code = "KGZ", Name = "Kyrgyzstan", CountryCode = "KGS", PhoneCode = 996, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 119, ISO2Code = "LA", ISO3Code = "LAO", Name = "Laos", CountryCode = "LAK", PhoneCode = 856, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 120, ISO2Code = "LV", ISO3Code = "LVA", Name = "Latvia", CountryCode = "EUR", PhoneCode = 371, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 121, ISO2Code = "LB", ISO3Code = "LBN", Name = "Lebanon", CountryCode = "LBP", PhoneCode = 961, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 122, ISO2Code = "LS", ISO3Code = "LSO", Name = "Lesotho", CountryCode = "LSL", PhoneCode = 266, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 123, ISO2Code = "LR", ISO3Code = "LBR", Name = "Liberia", CountryCode = "LRD", PhoneCode = 231, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 124, ISO2Code = "LY", ISO3Code = "LBY", Name = "Libya", CountryCode = "LYD", PhoneCode = 218, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 125, ISO2Code = "LI", ISO3Code = "LIE", Name = "Liechtenstein", CountryCode = "CHF", PhoneCode = 423, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 126, ISO2Code = "LT", ISO3Code = "LTU", Name = "Lithuania", CountryCode = "LTL", PhoneCode = 370, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 127, ISO2Code = "LU", ISO3Code = "LUX", Name = "Luxembourg", CountryCode = "EUR", PhoneCode = 352, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 128, ISO2Code = "MO", ISO3Code = "MAC", Name = "Macau S.A.R.", CountryCode = "MOP", PhoneCode = 853, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 129, ISO2Code = "MK", ISO3Code = "MKD", Name = "Macedonia", CountryCode = "MKD", PhoneCode = 389, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 130, ISO2Code = "MG", ISO3Code = "MDG", Name = "Madagascar", CountryCode = "MGA", PhoneCode = 261, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 131, ISO2Code = "MW", ISO3Code = "MWI", Name = "Malawi", CountryCode = "MWK", PhoneCode = 265, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 132, ISO2Code = "MY", ISO3Code = "MYS", Name = "Malaysia", CountryCode = "MYR", PhoneCode = 60, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 133, ISO2Code = "MV", ISO3Code = "MDV", Name = "Maldives", CountryCode = "MVR", PhoneCode = 960, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 134, ISO2Code = "ML", ISO3Code = "MLI", Name = "Mali", CountryCode = "XOF", PhoneCode = 223, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 135, ISO2Code = "MT", ISO3Code = "MLT", Name = "Malta", CountryCode = "EUR", PhoneCode = 356, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 136, ISO2Code = "IM", ISO3Code = "IMN", Name = "Man (Isle of)", CountryCode = "GBP", PhoneCode = -1580, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 137, ISO2Code = "MH", ISO3Code = "MHL", Name = "Marshall Islands", CountryCode = "USD", PhoneCode = 692, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 138, ISO2Code = "MQ", ISO3Code = "MTQ", Name = "Martinique", CountryCode = "EUR", PhoneCode = 596, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 139, ISO2Code = "MR", ISO3Code = "MRT", Name = "Mauritania", CountryCode = "MRO", PhoneCode = 222, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 140, ISO2Code = "MU", ISO3Code = "MUS", Name = "Mauritius", CountryCode = "MUR", PhoneCode = 230, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 141, ISO2Code = "YT", ISO3Code = "MYT", Name = "Mayotte", CountryCode = "EUR", PhoneCode = 262, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 142, ISO2Code = "MX", ISO3Code = "MEX", Name = "Mexico", CountryCode = "MXN", PhoneCode = 52, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 143, ISO2Code = "FM", ISO3Code = "FSM", Name = "Micronesia", CountryCode = "USD", PhoneCode = 691, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 144, ISO2Code = "MD", ISO3Code = "MDA", Name = "Moldova", CountryCode = "MDL", PhoneCode = 373, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 145, ISO2Code = "MC", ISO3Code = "MCO", Name = "Monaco", CountryCode = "EUR", PhoneCode = 377, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 146, ISO2Code = "MN", ISO3Code = "MNG", Name = "Mongolia", CountryCode = "MNT", PhoneCode = 976, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 147, ISO2Code = "ME", ISO3Code = "MNE", Name = "Montenegro", CountryCode = "EUR", PhoneCode = 382, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 148, ISO2Code = "MS", ISO3Code = "MSR", Name = "Montserrat", CountryCode = "XCD", PhoneCode = -663, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 149, ISO2Code = "MA", ISO3Code = "MAR", Name = "Morocco", CountryCode = "MAD", PhoneCode = 212, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 150, ISO2Code = "MZ", ISO3Code = "MOZ", Name = "Mozambique", CountryCode = "MZN", PhoneCode = 258, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 151, ISO2Code = "MM", ISO3Code = "MMR", Name = "Myanmar", CountryCode = "MMK", PhoneCode = 95, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 152, ISO2Code = "NA", ISO3Code = "NAM", Name = "Namibia", CountryCode = "NAD", PhoneCode = 264, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 153, ISO2Code = "NR", ISO3Code = "NRU", Name = "Nauru", CountryCode = "AUD", PhoneCode = 674, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 154, ISO2Code = "NP", ISO3Code = "NPL", Name = "Nepal", CountryCode = "NPR", PhoneCode = 977, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 155, ISO2Code = "AN", ISO3Code = "ANT", Name = "Netherlands Antilles", CountryCode = null, PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 156, ISO2Code = "NL", ISO3Code = "NLD", Name = "Netherlands The", CountryCode = "EUR", PhoneCode = 31, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 157, ISO2Code = "NC", ISO3Code = "NCL", Name = "New Caledonia", CountryCode = "XPF", PhoneCode = 687, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 158, ISO2Code = "NZ", ISO3Code = "NZL", Name = "New Zealand", CountryCode = "NZD", PhoneCode = 64, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 159, ISO2Code = "NI", ISO3Code = "NIC", Name = "Nicaragua", CountryCode = "NIO", PhoneCode = 505, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 160, ISO2Code = "NE", ISO3Code = "NER", Name = "Niger", CountryCode = "XOF", PhoneCode = 227, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 161, ISO2Code = "NG", ISO3Code = "NGA", Name = "Nigeria", CountryCode = "NGN", PhoneCode = 234, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 162, ISO2Code = "NU", ISO3Code = "NIU", Name = "Niue", CountryCode = "NZD", PhoneCode = 683, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 163, ISO2Code = "NF", ISO3Code = "NFK", Name = "Norfolk Island", CountryCode = "AUD", PhoneCode = 672, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 164, ISO2Code = "MP", ISO3Code = "MNP", Name = "Northern Mariana Islands", CountryCode = "USD", PhoneCode = -669, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 165, ISO2Code = "NO", ISO3Code = "NOR", Name = "Norway", CountryCode = "NOK", PhoneCode = 47, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 166, ISO2Code = "OM", ISO3Code = "OMN", Name = "Oman", CountryCode = "OMR", PhoneCode = 968, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 167, ISO2Code = "PK", ISO3Code = "PAK", Name = "Pakistan", CountryCode = "PKR", PhoneCode = 92, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 168, ISO2Code = "PW", ISO3Code = "PLW", Name = "Palau", CountryCode = "USD", PhoneCode = 680, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 169, ISO2Code = "PS", ISO3Code = "PSE", Name = "Palestinian Territory Occupied", CountryCode = "ILS", PhoneCode = 970, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 170, ISO2Code = "PA", ISO3Code = "PAN", Name = "Panama", CountryCode = "PAB", PhoneCode = 507, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 171, ISO2Code = "PG", ISO3Code = "PNG", Name = "Papua new Guinea", CountryCode = "PGK", PhoneCode = 675, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 172, ISO2Code = "PY", ISO3Code = "PRY", Name = "Paraguay", CountryCode = "PYG", PhoneCode = 595, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 173, ISO2Code = "PE", ISO3Code = "PER", Name = "Peru", CountryCode = "PEN", PhoneCode = 51, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 174, ISO2Code = "PH", ISO3Code = "PHL", Name = "Philippines", CountryCode = "PHP", PhoneCode = 63, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 175, ISO2Code = "PN", ISO3Code = "PCN", Name = "Pitcairn Island", CountryCode = "NZD", PhoneCode = 870, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 176, ISO2Code = "PL", ISO3Code = "POL", Name = "Poland", CountryCode = "PLN", PhoneCode = 48, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 177, ISO2Code = "PT", ISO3Code = "PRT", Name = "Portugal", CountryCode = "EUR", PhoneCode = 351, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 178, ISO2Code = "PR", ISO3Code = "PRI", Name = "Puerto Rico", CountryCode = "USD", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 179, ISO2Code = "QA", ISO3Code = "QAT", Name = "Qatar", CountryCode = "QAR", PhoneCode = 974, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 180, ISO2Code = "RE", ISO3Code = "REU", Name = "Reunion", CountryCode = "EUR", PhoneCode = 262, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 181, ISO2Code = "RO", ISO3Code = "ROU", Name = "Romania", CountryCode = "RON", PhoneCode = 40, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 182, ISO2Code = "RU", ISO3Code = "RUS", Name = "Russia", CountryCode = "RUB", PhoneCode = 7, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 183, ISO2Code = "RW", ISO3Code = "RWA", Name = "Rwanda", CountryCode = "RWF", PhoneCode = 250, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 184, ISO2Code = "SH", ISO3Code = "SHN", Name = "Saint Helena", CountryCode = "SHP", PhoneCode = 290, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 185, ISO2Code = "KN", ISO3Code = "KNA", Name = "Saint Kitts And Nevis", CountryCode = "XCD", PhoneCode = -868, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 186, ISO2Code = "LC", ISO3Code = "LCA", Name = "Saint Lucia", CountryCode = "XCD", PhoneCode = -757, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 187, ISO2Code = "PM", ISO3Code = "SPM", Name = "Saint Pierre and Miquelon", CountryCode = "EUR", PhoneCode = 508, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 188, ISO2Code = "VC", ISO3Code = "VCT", Name = "Saint Vincent And The Grenadines", CountryCode = "XCD", PhoneCode = -783, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 189, ISO2Code = "BL", ISO3Code = "BLM", Name = "Saint-Barthelemy", CountryCode = "EUR", PhoneCode = 590, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 190, ISO2Code = "MF", ISO3Code = "MAF", Name = "Saint-Martin (French part)", CountryCode = "EUR", PhoneCode = 590, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 191, ISO2Code = "WS", ISO3Code = "WSM", Name = "Samoa", CountryCode = "WST", PhoneCode = 685, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 192, ISO2Code = "SM", ISO3Code = "SMR", Name = "San Marino", CountryCode = "EUR", PhoneCode = 378, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 193, ISO2Code = "ST", ISO3Code = "STP", Name = "Sao Tome and Principe", CountryCode = "STD", PhoneCode = 239, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 194, ISO2Code = "SA", ISO3Code = "SAU", Name = "Saudi Arabia", CountryCode = "SAR", PhoneCode = 966, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 195, ISO2Code = "SN", ISO3Code = "SEN", Name = "Senegal", CountryCode = "XOF", PhoneCode = 221, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 196, ISO2Code = "RS", ISO3Code = "SRB", Name = "Serbia", CountryCode = "RSD", PhoneCode = 381, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 197, ISO2Code = "SC", ISO3Code = "SYC", Name = "Seychelles", CountryCode = "SCR", PhoneCode = 248, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 198, ISO2Code = "SL", ISO3Code = "SLE", Name = "Sierra Leone", CountryCode = "SLL", PhoneCode = 232, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 199, ISO2Code = "SG", ISO3Code = "SGP", Name = "Singapore", CountryCode = "SGD", PhoneCode = 65, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 200, ISO2Code = "SK", ISO3Code = "SVK", Name = "Slovakia", CountryCode = "EUR", PhoneCode = 421, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 201, ISO2Code = "SI", ISO3Code = "SVN", Name = "Slovenia", CountryCode = "EUR", PhoneCode = 386, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 202, ISO2Code = "SB", ISO3Code = "SLB", Name = "Solomon Islands", CountryCode = "SBD", PhoneCode = 677, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 203, ISO2Code = "SO", ISO3Code = "SOM", Name = "Somalia", CountryCode = "SOS", PhoneCode = 252, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 204, ISO2Code = "ZA", ISO3Code = "ZAF", Name = "South Africa", CountryCode = "ZAR", PhoneCode = 27, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 205, ISO2Code = "GS", ISO3Code = "SGS", Name = "South Georgia", CountryCode = "GBP", PhoneCode = null, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 206, ISO2Code = "SS", ISO3Code = "SSD", Name = "South Sudan", CountryCode = "SSP", PhoneCode = 211, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 207, ISO2Code = "ES", ISO3Code = "ESP", Name = "Spain", CountryCode = "EUR", PhoneCode = 34, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 208, ISO2Code = "LK", ISO3Code = "LKA", Name = "Sri Lanka", CountryCode = "LKR", PhoneCode = 94, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 209, ISO2Code = "SD", ISO3Code = "SDN", Name = "Sudan", CountryCode = "SDG", PhoneCode = 249, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 210, ISO2Code = "SR", ISO3Code = "SUR", Name = "Suriname", CountryCode = "SRD", PhoneCode = 597, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 211, ISO2Code = "SJ", ISO3Code = "SJM", Name = "Svalbard And Jan Mayen Islands", CountryCode = "NOK", PhoneCode = 47, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 212, ISO2Code = "SZ", ISO3Code = "SWZ", Name = "Swaziland", CountryCode = "SZL", PhoneCode = 268, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 213, ISO2Code = "SE", ISO3Code = "SWE", Name = "Sweden", CountryCode = "SEK", PhoneCode = 46, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 214, ISO2Code = "CH", ISO3Code = "CHE", Name = "Switzerland", CountryCode = "CHF", PhoneCode = 41, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 215, ISO2Code = "SY", ISO3Code = "SYR", Name = "Syria", CountryCode = "SYP", PhoneCode = 963, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 216, ISO2Code = "TW", ISO3Code = "TWN", Name = "Taiwan", CountryCode = "TWD", PhoneCode = 886, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 217, ISO2Code = "TJ", ISO3Code = "TJK", Name = "Tajikistan", CountryCode = "TJS", PhoneCode = 992, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 218, ISO2Code = "TZ", ISO3Code = "TZA", Name = "Tanzania", CountryCode = "TZS", PhoneCode = 255, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 219, ISO2Code = "TH", ISO3Code = "THA", Name = "Thailand", CountryCode = "THB", PhoneCode = 66, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 220, ISO2Code = "TG", ISO3Code = "TGO", Name = "Togo", CountryCode = "XOF", PhoneCode = 228, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 221, ISO2Code = "TK", ISO3Code = "TKL", Name = "Tokelau", CountryCode = "NZD", PhoneCode = 690, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 222, ISO2Code = "TO", ISO3Code = "TON", Name = "Tonga", CountryCode = "TOP", PhoneCode = 676, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 223, ISO2Code = "TT", ISO3Code = "TTO", Name = "Trinidad And Tobago", CountryCode = "TTD", PhoneCode = -867, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 224, ISO2Code = "TN", ISO3Code = "TUN", Name = "Tunisia", CountryCode = "TND", PhoneCode = 216, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 225, ISO2Code = "TR", ISO3Code = "TUR", Name = "Turkey", CountryCode = "TRY", PhoneCode = 90, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 226, ISO2Code = "TM", ISO3Code = "TKM", Name = "Turkmenistan", CountryCode = "TMT", PhoneCode = 993, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 227, ISO2Code = "TC", ISO3Code = "TCA", Name = "Turks And Caicos Islands", CountryCode = "USD", PhoneCode = -648, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 228, ISO2Code = "TV", ISO3Code = "TUV", Name = "Tuvalu", CountryCode = "AUD", PhoneCode = 688, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 229, ISO2Code = "UG", ISO3Code = "UGA", Name = "Uganda", CountryCode = "UGX", PhoneCode = 256, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 230, ISO2Code = "UA", ISO3Code = "UKR", Name = "Ukraine", CountryCode = "UAH", PhoneCode = 380, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 231, ISO2Code = "AE", ISO3Code = "ARE", Name = "United Arab Emirates", CountryCode = "AED", PhoneCode = 971, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 232, ISO2Code = "GB", ISO3Code = "GBR", Name = "United Kingdom", CountryCode = "GBP", PhoneCode = 44, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 233, ISO2Code = "US", ISO3Code = "USA", Name = "United States", CountryCode = "USD", PhoneCode = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 234, ISO2Code = "UM", ISO3Code = "UMI", Name = "United States Minor Outlying Islands", CountryCode = "USD", PhoneCode = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 235, ISO2Code = "UY", ISO3Code = "URY", Name = "Uruguay", CountryCode = "UYU", PhoneCode = 598, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 236, ISO2Code = "UZ", ISO3Code = "UZB", Name = "Uzbekistan", CountryCode = "UZS", PhoneCode = 998, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 237, ISO2Code = "VU", ISO3Code = "VUT", Name = "Vanuatu", CountryCode = "VUV", PhoneCode = 678, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 238, ISO2Code = "VA", ISO3Code = "VAT", Name = "Vatican City State (Holy See)", CountryCode = "EUR", PhoneCode = 379, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 239, ISO2Code = "VE", ISO3Code = "VEN", Name = "Venezuela", CountryCode = "VEF", PhoneCode = 58, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 240, ISO2Code = "VN", ISO3Code = "VNM", Name = "Vietnam", CountryCode = "VND", PhoneCode = 84, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 241, ISO2Code = "VG", ISO3Code = "VGB", Name = "Virgin Islands (British)", CountryCode = "USD", PhoneCode = -283, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 242, ISO2Code = "VI", ISO3Code = "VIR", Name = "Virgin Islands (US)", CountryCode = "USD", PhoneCode = -339, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 243, ISO2Code = "WF", ISO3Code = "WLF", Name = "Wallis And Futuna Islands", CountryCode = "XPF", PhoneCode = 681, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 244, ISO2Code = "EH", ISO3Code = "ESH", Name = "Western Sahara", CountryCode = "MAD", PhoneCode = 212, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 245, ISO2Code = "YE", ISO3Code = "YEM", Name = "Yemen", CountryCode = "YER", PhoneCode = 967, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 246, ISO2Code = "ZM", ISO3Code = "ZMB", Name = "Zambia", CountryCode = "ZMK", PhoneCode = 260, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new Country { Id = 247, ISO2Code = "ZW", ISO3Code = "ZWE", Name = "Zimbabwe", CountryCode = "ZWL", PhoneCode = 263, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now }

             );
        }
    }
}

