using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MM.ClientModels
{
    public partial class CustomField
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public int TablePrimaryKeyValue { get; set; }
        public int? Int1 { get; set; }
        public int? Int2 { get; set; }
        public int? Int3 { get; set; }
        public int? Int4 { get; set; }
        public int? Int5 { get; set; }
        public int? Int6 { get; set; }
        public int? Int7 { get; set; }
        public int? Int8 { get; set; }
        public int? Int9 { get; set; }
        public int? Int10 { get; set; }
        public int? Int11 { get; set; }
        public int? Int12 { get; set; }
        public int? Int13 { get; set; }
        public int? Int14 { get; set; }
        public int? Int15 { get; set; }
        public int? Int16 { get; set; }
        public int? Int17 { get; set; }
        public int? Int18 { get; set; }
        public int? Int19 { get; set; }
        public int? Int20 { get; set; }

        public int? Lookup1 { get; set; }
        public int? Lookup2 { get; set; }
        public int? Lookup3 { get; set; }
        public int? Lookup4 { get; set; }
        public int? Lookup5 { get; set; }
        public int? Lookup6 { get; set; }
        public int? Lookup7 { get; set; }
        public int? Lookup8 { get; set; }
        public int? Lookup9 { get; set; }
        public int? Lookup10 { get; set; }
        public int? Lookup11 { get; set; }
        public int? Lookup12 { get; set; }
        public int? Lookup13 { get; set; }
        public int? Lookup14 { get; set; }
        public int? Lookup15 { get; set; }
        public int? Lookup16 { get; set; }
        public int? Lookup17 { get; set; }
        public int? Lookup18 { get; set; }
        public int? Lookup19 { get; set; }
        public int? Lookup20 { get; set; }

        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public string Text9 { get; set; }
        public string Text10 { get; set; }
        public string Text11 { get; set; }
        public string Text12 { get; set; }
        public string Text13 { get; set; }
        public string Text14 { get; set; }
        public string Text15 { get; set; }
        public string Text16 { get; set; }
        public string Text17 { get; set; }
        public string Text18 { get; set; }
        public string Text19 { get; set; }
        public string Text20 { get; set; }

        public DateTime? Datetime1 { get; set; }
        public DateTime? Datetime2 { get; set; }
        public DateTime? Datetime3 { get; set; }
        public DateTime? Datetime4 { get; set; }
        public DateTime? Datetime5 { get; set; }
        public DateTime? Datetime6 { get; set; }
        public DateTime? Datetime7 { get; set; }
        public DateTime? Datetime8 { get; set; }
        public DateTime? Datetime9 { get; set; }
        public DateTime? Datetime10 { get; set; }
        public DateTime? Datetime11 { get; set; }
        public DateTime? Datetime12 { get; set; }
        public DateTime? Datetime13 { get; set; }
        public DateTime? Datetime14 { get; set; }
        public DateTime? Datetime15 { get; set; }
        public DateTime? Datetime16 { get; set; }
        public DateTime? Datetime17 { get; set; }
        public DateTime? Datetime18 { get; set; }
        public DateTime? Datetime19 { get; set; }
        public DateTime? Datetime20 { get; set; }

        public decimal? Decimal1 { get; set; }
        public decimal? Decimal2 { get; set; }
        public decimal? Decimal3 { get; set; }
        public decimal? Decimal4 { get; set; }
        public decimal? Decimal5 { get; set; }
        public decimal? Decimal6 { get; set; }
        public decimal? Decimal7 { get; set; }
        public decimal? Decimal8 { get; set; }
        public decimal? Decimal9 { get; set; }
        public decimal? Decimal10 { get; set; }
        public decimal? Decimal11 { get; set; }
        public decimal? Decimal12 { get; set; }
        public decimal? Decimal13 { get; set; }
        public decimal? Decimal14 { get; set; }
        public decimal? Decimal15 { get; set; }
        public decimal? Decimal16 { get; set; }
        public decimal? Decimal17 { get; set; }
        public decimal? Decimal18 { get; set; }
        public decimal? Decimal19 { get; set; }
        public decimal? Decimal20 { get; set; }


        //public int? Int21 { get; set; }
        //public int? Int22 { get; set; }
        //public int? Int23 { get; set; }
        //public int? Int24 { get; set; }
        //public int? Int25 { get; set; }
        //public int? Int26 { get; set; }
        //public int? Int27 { get; set; }
        //public int? Int28 { get; set; }
        //public int? Int29 { get; set; }
        //public int? Int30 { get; set; }
        //public int? Int31 { get; set; }
        //public int? Int32 { get; set; }
        //public int? Int33 { get; set; }
        //public int? Int34 { get; set; }
        //public int? Int35 { get; set; }
        //public int? Int36 { get; set; }
        //public int? Int37 { get; set; }
        //public int? Int38 { get; set; }
        //public int? Int39 { get; set; }
        //public int? Int40 { get; set; }
        //public int? Int41 { get; set; }
        //public int? Int42 { get; set; }
        //public int? Int43 { get; set; }
        //public int? Int44 { get; set; }
        //public int? Int45 { get; set; }
        //public int? Int46 { get; set; }
        //public int? Int47 { get; set; }
        //public int? Int48 { get; set; }
        //public int? Int49 { get; set; }
        //public int? Int50 { get; set; }
        //public int? Int51 { get; set; }
        //public int? Int52 { get; set; }
        //public int? Int53 { get; set; }
        //public int? Int54 { get; set; }
        //public int? Int55 { get; set; }
        //public int? Int56 { get; set; }
        //public int? Int57 { get; set; }
        //public int? Int58 { get; set; }
        //public int? Int59 { get; set; }
        //public int? Int60 { get; set; }
        //public int? Int61 { get; set; }
        //public int? Int62 { get; set; }
        //public int? Int63 { get; set; }
        //public int? Int64 { get; set; }
        //public int? Int65 { get; set; }
        //public int? Int66 { get; set; }
        //public int? Int67 { get; set; }
        //public int? Int68 { get; set; }
        //public int? Int69 { get; set; }
        //public int? Int70 { get; set; }
        //public int? Int71 { get; set; }
        //public int? Int72 { get; set; }
        //public int? Int73 { get; set; }
        //public int? Int74 { get; set; }
        //public int? Int75 { get; set; }
        //public int? Int76 { get; set; }
        //public int? Int77 { get; set; }
        //public int? Int78 { get; set; }
        //public int? Int79 { get; set; }
        //public int? Int80 { get; set; }
        //public int? Int81 { get; set; }
        //public int? Int82 { get; set; }
        //public int? Int83 { get; set; }
        //public int? Int84 { get; set; }
        //public int? Int85 { get; set; }
        //public int? Int86 { get; set; }
        //public int? Int87 { get; set; }
        //public int? Int88 { get; set; }
        //public int? Int89 { get; set; }
        //public int? Int90 { get; set; }
        //public int? Int91 { get; set; }
        //public int? Int92 { get; set; }
        //public int? Int93 { get; set; }
        //public int? Int94 { get; set; }
        //public int? Int95 { get; set; }
        //public int? Int96 { get; set; }
        //public int? Int97 { get; set; }
        //public int? Int98 { get; set; }
        //public int? Int99 { get; set; }
        //public int? Int100 { get; set; }


        //public int? Lookup21 { get; set; }
        //public int? Lookup22 { get; set; }
        //public int? Lookup23 { get; set; }
        //public int? Lookup24 { get; set; }
        //public int? Lookup25 { get; set; }
        //public int? Lookup26 { get; set; }
        //public int? Lookup27 { get; set; }
        //public int? Lookup28 { get; set; }
        //public int? Lookup29 { get; set; }
        //public int? Lookup30 { get; set; }
        //public int? Lookup31 { get; set; }
        //public int? Lookup32 { get; set; }
        //public int? Lookup33 { get; set; }
        //public int? Lookup34 { get; set; }
        //public int? Lookup35 { get; set; }
        //public int? Lookup36 { get; set; }
        //public int? Lookup37 { get; set; }
        //public int? Lookup38 { get; set; }
        //public int? Lookup39 { get; set; }
        //public int? Lookup40 { get; set; }
        //public int? Lookup41 { get; set; }
        //public int? Lookup42 { get; set; }
        //public int? Lookup43 { get; set; }
        //public int? Lookup44 { get; set; }
        //public int? Lookup45 { get; set; }
        //public int? Lookup46 { get; set; }
        //public int? Lookup47 { get; set; }
        //public int? Lookup48 { get; set; }
        //public int? Lookup49 { get; set; }
        //public int? Lookup50 { get; set; }
        //public int? Lookup51 { get; set; }
        //public int? Lookup52 { get; set; }
        //public int? Lookup53 { get; set; }
        //public int? Lookup54 { get; set; }
        //public int? Lookup55 { get; set; }
        //public int? Lookup56 { get; set; }
        //public int? Lookup57 { get; set; }
        //public int? Lookup58 { get; set; }
        //public int? Lookup59 { get; set; }
        //public int? Lookup60 { get; set; }
        //public int? Lookup61 { get; set; }
        //public int? Lookup62 { get; set; }
        //public int? Lookup63 { get; set; }
        //public int? Lookup64 { get; set; }
        //public int? Lookup65 { get; set; }
        //public int? Lookup66 { get; set; }
        //public int? Lookup67 { get; set; }
        //public int? Lookup68 { get; set; }
        //public int? Lookup69 { get; set; }
        //public int? Lookup70 { get; set; }
        //public int? Lookup71 { get; set; }
        //public int? Lookup72 { get; set; }
        //public int? Lookup73 { get; set; }
        //public int? Lookup74 { get; set; }
        //public int? Lookup75 { get; set; }
        //public int? Lookup76 { get; set; }
        //public int? Lookup77 { get; set; }
        //public int? Lookup78 { get; set; }
        //public int? Lookup79 { get; set; }
        //public int? Lookup80 { get; set; }
        //public int? Lookup81 { get; set; }
        //public int? Lookup82 { get; set; }
        //public int? Lookup83 { get; set; }
        //public int? Lookup84 { get; set; }
        //public int? Lookup85 { get; set; }
        //public int? Lookup86 { get; set; }
        //public int? Lookup87 { get; set; }
        //public int? Lookup88 { get; set; }
        //public int? Lookup89 { get; set; }
        //public int? Lookup90 { get; set; }
        //public int? Lookup91 { get; set; }
        //public int? Lookup92 { get; set; }
        //public int? Lookup93 { get; set; }
        //public int? Lookup94 { get; set; }
        //public int? Lookup95 { get; set; }
        //public int? Lookup96 { get; set; }
        //public int? Lookup97 { get; set; }
        //public int? Lookup98 { get; set; }
        //public int? Lookup99 { get; set; }
        //public int? Lookup100 { get; set; }
        //public int? Lookup101 { get; set; }
        //public int? Lookup102 { get; set; }
        //public int? Lookup103 { get; set; }
        //public int? Lookup104 { get; set; }
        //public int? Lookup105 { get; set; }
        //public int? Lookup106 { get; set; }
        //public int? Lookup107 { get; set; }
        //public int? Lookup108 { get; set; }
        //public int? Lookup109 { get; set; }
        //public int? Lookup110 { get; set; }
        //public string Text21 { get; set; }
        //public string Text22 { get; set; }
        //public string Text23 { get; set; }
        //public string Text24 { get; set; }
        //public string Text25 { get; set; }
        //public string Text26 { get; set; }
        //public string Text27 { get; set; }
        //public string Text28 { get; set; }
        //public string Text29 { get; set; }
        //public string Text30 { get; set; }
        //public string Text31 { get; set; }
        //public string Text32 { get; set; }
        //public string Text33 { get; set; }
        //public string Text34 { get; set; }
        //public string Text35 { get; set; }
        //public string Text36 { get; set; }
        //public string Text37 { get; set; }
        //public string Text38 { get; set; }
        //public string Text39 { get; set; }
        //public string Text40 { get; set; }
        //public string Text41 { get; set; }
        //public string Text42 { get; set; }
        //public string Text43 { get; set; }
        //public string Text44 { get; set; }
        //public string Text45 { get; set; }
        //public string Text46 { get; set; }
        //public string Text47 { get; set; }
        //public string Text48 { get; set; }
        //public string Text49 { get; set; }
        //public string Text50 { get; set; }
        //public string Text51 { get; set; }
        //public string Text52 { get; set; }
        //public string Text53 { get; set; }
        //public string Text54 { get; set; }
        //public string Text55 { get; set; }
        //public string Text56 { get; set; }
        //public string Text57 { get; set; }
        //public string Text58 { get; set; }
        //public string Text59 { get; set; }
        //public string Text60 { get; set; }
        //public string Text61 { get; set; }
        //public string Text62 { get; set; }
        //public string Text63 { get; set; }
        //public string Text64 { get; set; }
        //public string Text65 { get; set; }
        //public string Text66 { get; set; }
        //public string Text67 { get; set; }
        //public string Text68 { get; set; }
        //public string Text69 { get; set; }
        //public string Text70 { get; set; }
        //public string Text71 { get; set; }
        //public string Text72 { get; set; }
        //public string Text73 { get; set; }
        //public string Text74 { get; set; }
        //public string Text75 { get; set; }
        //public string Text76 { get; set; }
        //public string Text77 { get; set; }
        //public string Text78 { get; set; }
        //public string Text79 { get; set; }
        //public string Text80 { get; set; }
        //public string Text81 { get; set; }
        //public string Text82 { get; set; }
        //public string Text83 { get; set; }
        //public string Text84 { get; set; }
        //public string Text85 { get; set; }
        //public string Text86 { get; set; }
        //public string Text87 { get; set; }
        //public string Text88 { get; set; }
        //public string Text89 { get; set; }
        //public string Text90 { get; set; }
        //public string Text91 { get; set; }
        //public string Text92 { get; set; }
        //public string Text93 { get; set; }
        //public string Text94 { get; set; }
        //public string Text95 { get; set; }
        //public string Text96 { get; set; }
        //public string Text97 { get; set; }
        //public string Text98 { get; set; }
        //public string Text99 { get; set; }
        //public string Text100 { get; set; }

        //public DateTime? Datetime21 { get; set; }
        //public DateTime? Datetime22 { get; set; }
        //public DateTime? Datetime23 { get; set; }
        //public DateTime? Datetime24 { get; set; }
        //public DateTime? Datetime25 { get; set; }
        //public DateTime? Datetime26 { get; set; }
        //public DateTime? Datetime27 { get; set; }
        //public DateTime? Datetime28 { get; set; }
        //public DateTime? Datetime29 { get; set; }
        //public DateTime? Datetime30 { get; set; }
        //public DateTime? Datetime31 { get; set; }
        //public DateTime? Datetime32 { get; set; }
        //public DateTime? Datetime33 { get; set; }
        //public DateTime? Datetime34 { get; set; }
        //public DateTime? Datetime35 { get; set; }
        //public DateTime? Datetime36 { get; set; }
        //public DateTime? Datetime37 { get; set; }
        //public DateTime? Datetime38 { get; set; }
        //public DateTime? Datetime39 { get; set; }
        //public DateTime? Datetime40 { get; set; }
        //public DateTime? Datetime41 { get; set; }
        //public DateTime? Datetime42 { get; set; }
        //public DateTime? Datetime43 { get; set; }
        //public DateTime? Datetime44 { get; set; }
        //public DateTime? Datetime45 { get; set; }
        //public DateTime? Datetime46 { get; set; }
        //public DateTime? Datetime47 { get; set; }
        //public DateTime? Datetime48 { get; set; }
        //public DateTime? Datetime49 { get; set; }
        //public DateTime? Datetime50 { get; set; }
        //public DateTime? Datetime51 { get; set; }
        //public DateTime? Datetime52 { get; set; }
        //public DateTime? Datetime53 { get; set; }
        //public DateTime? Datetime54 { get; set; }
        //public DateTime? Datetime55 { get; set; }
        //public DateTime? Datetime56 { get; set; }
        //public DateTime? Datetime57 { get; set; }
        //public DateTime? Datetime58 { get; set; }
        //public DateTime? Datetime59 { get; set; }
        //public DateTime? Datetime60 { get; set; }
        //public DateTime? Datetime61 { get; set; }
        //public DateTime? Datetime62 { get; set; }
        //public DateTime? Datetime63 { get; set; }
        //public DateTime? Datetime64 { get; set; }
        //public DateTime? Datetime65 { get; set; }
        //public DateTime? Datetime66 { get; set; }
        //public DateTime? Datetime67 { get; set; }
        //public DateTime? Datetime68 { get; set; }
        //public DateTime? Datetime69 { get; set; }
        //public DateTime? Datetime70 { get; set; }
        //public DateTime? Datetime71 { get; set; }
        //public DateTime? Datetime72 { get; set; }
        //public DateTime? Datetime73 { get; set; }
        //public DateTime? Datetime74 { get; set; }
        //public DateTime? Datetime75 { get; set; }
        //public DateTime? Datetime76 { get; set; }
        //public DateTime? Datetime77 { get; set; }
        //public DateTime? Datetime78 { get; set; }
        //public DateTime? Datetime79 { get; set; }
        //public DateTime? Datetime80 { get; set; }
        //public DateTime? Datetime81 { get; set; }
        //public DateTime? Datetime82 { get; set; }
        //public DateTime? Datetime83 { get; set; }
        //public DateTime? Datetime84 { get; set; }
        //public DateTime? Datetime85 { get; set; }
        //public DateTime? Datetime86 { get; set; }
        //public DateTime? Datetime87 { get; set; }
        //public DateTime? Datetime88 { get; set; }
        //public DateTime? Datetime89 { get; set; }
        //public DateTime? Datetime90 { get; set; }
        //public DateTime? Datetime91 { get; set; }
        //public DateTime? Datetime92 { get; set; }
        //public DateTime? Datetime93 { get; set; }
        //public DateTime? Datetime94 { get; set; }
        //public DateTime? Datetime95 { get; set; }
        //public DateTime? Datetime96 { get; set; }
        //public DateTime? Datetime97 { get; set; }
        //public DateTime? Datetime98 { get; set; }
        //public DateTime? Datetime99 { get; set; }
        //public DateTime? Datetime100 { get; set; }

        //public decimal? Decimal21 { get; set; }
        //public decimal? Decimal22 { get; set; }
        //public decimal? Decimal23 { get; set; }
        //public decimal? Decimal24 { get; set; }
        //public decimal? Decimal25 { get; set; }
        //public decimal? Decimal26 { get; set; }
        //public decimal? Decimal27 { get; set; }
        //public decimal? Decimal28 { get; set; }
        //public decimal? Decimal29 { get; set; }
        //public decimal? Decimal30 { get; set; }
        //public decimal? Decimal31 { get; set; }
        //public decimal? Decimal32 { get; set; }
        //public decimal? Decimal33 { get; set; }
        //public decimal? Decimal34 { get; set; }
        //public decimal? Decimal35 { get; set; }
        //public decimal? Decimal36 { get; set; }
        //public decimal? Decimal37 { get; set; }
        //public decimal? Decimal38 { get; set; }
        //public decimal? Decimal39 { get; set; }
        //public decimal? Decimal40 { get; set; }
        //public decimal? Decimal41 { get; set; }
        //public decimal? Decimal42 { get; set; }
        //public decimal? Decimal43 { get; set; }
        //public decimal? Decimal44 { get; set; }
        //public decimal? Decimal45 { get; set; }
        //public decimal? Decimal46 { get; set; }
        //public decimal? Decimal47 { get; set; }
        //public decimal? Decimal48 { get; set; }
        //public decimal? Decimal49 { get; set; }
        //public decimal? Decimal50 { get; set; }
        //public decimal? Decimal51 { get; set; }
        //public decimal? Decimal52 { get; set; }
        //public decimal? Decimal53 { get; set; }
        //public decimal? Decimal54 { get; set; }
        //public decimal? Decimal55 { get; set; }
        //public decimal? Decimal56 { get; set; }
        //public decimal? Decimal57 { get; set; }
        //public decimal? Decimal58 { get; set; }
        //public decimal? Decimal59 { get; set; }
        //public decimal? Decimal60 { get; set; }
        //public decimal? Decimal61 { get; set; }
        //public decimal? Decimal62 { get; set; }
        //public decimal? Decimal63 { get; set; }
        //public decimal? Decimal64 { get; set; }
        //public decimal? Decimal65 { get; set; }
        //public decimal? Decimal66 { get; set; }
        //public decimal? Decimal67 { get; set; }
        //public decimal? Decimal68 { get; set; }
        //public decimal? Decimal69 { get; set; }
        //public decimal? Decimal70 { get; set; }
        //public decimal? Decimal71 { get; set; }
        //public decimal? Decimal72 { get; set; }
        //public decimal? Decimal73 { get; set; }
        //public decimal? Decimal74 { get; set; }
        //public decimal? Decimal75 { get; set; }
        //public decimal? Decimal76 { get; set; }
        //public decimal? Decimal77 { get; set; }
        //public decimal? Decimal78 { get; set; }
        //public decimal? Decimal79 { get; set; }
        //public decimal? Decimal80 { get; set; }
        //public decimal? Decimal81 { get; set; }
        //public decimal? Decimal82 { get; set; }
        //public decimal? Decimal83 { get; set; }
        //public decimal? Decimal84 { get; set; }
        //public decimal? Decimal85 { get; set; }
        //public decimal? Decimal86 { get; set; }
        //public decimal? Decimal87 { get; set; }
        //public decimal? Decimal88 { get; set; }
        //public decimal? Decimal89 { get; set; }
        //public decimal? Decimal90 { get; set; }
        //public decimal? Decimal91 { get; set; }
        //public decimal? Decimal92 { get; set; }
        //public decimal? Decimal93 { get; set; }
        //public decimal? Decimal94 { get; set; }
        //public decimal? Decimal95 { get; set; }
        //public decimal? Decimal96 { get; set; }
        //public decimal? Decimal97 { get; set; }
        //public decimal? Decimal98 { get; set; }
        //public decimal? Decimal99 { get; set; }
        //public decimal? Decimal100 { get; set; }




        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
    }

    public partial class CustomFieldConfiguration : IEntityTypeConfiguration<CustomField>
    {
        public void Configure(EntityTypeBuilder<CustomField> builder)
        {

        }

    }
    public static partial class Seeder
    {
        public static void SeedCustomField(this ModelBuilder modelBuilder)
        {

        }
    }
}
