using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MM.ClientModels
{
    public partial class State
    {
        public State()
        {
            Address = new HashSet<Address>();
            City = new HashSet<City>();
        }

        public int Id { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<City> City { get; set; }
    }
    public partial class StateConfiguration : IEntityTypeConfiguration<State>
    {
        public void Configure(EntityTypeBuilder<State> builder)
        {
   builder.Property(e => e.CreatedOn).HasColumnType("datetime");

                builder.Property(e => e.ModifiedOn).HasColumnType("datetime");

                builder.Property(e => e.Name).HasMaxLength(100);

                builder.HasOne(d => d.Country)
                    .WithMany(p => p.State)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_State_Country");
        }

    }
    public static partial class Seeder
    {
        public static void SeedState(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<State>().HasData(

               new State { Id = 1, Name = "Eastern Cape", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 2, Name = "Free State", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 3, Name = "Gauteng", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 4, Name = "KwaZulu-Natal", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 5, Name = "Limpopo", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 6, Name = "Mpumalanga", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 7, Name = "North West", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 8, Name = "Northern Cape", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 9, Name = "Western Cape", CountryId = 1, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 10, Name = "Australian Capital Territory", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 11, Name = "New South Wales", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 12, Name = "Northern Territory", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 13, Name = "Queensland", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 14, Name = "South Australia", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 15, Name = "Tasmania", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 16, Name = "Victoria", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 17, Name = "Western Australia", CountryId = 2, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 18, Name = "Andaman and Nicobar Islands", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 19, Name = "Andhra Pradesh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 20, Name = "Arunachal Pradesh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 21, Name = "Assam", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 22, Name = "Bihar", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 23, Name = "Chandigarh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 24, Name = "Chhattisgarh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 25, Name = "Dadra and Nagar Haveli", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 26, Name = "Daman and Diu", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 27, Name = "Delhi", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 28, Name = "Goa", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 29, Name = "Gujarat", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 30, Name = "Haryana", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 31, Name = "Himachal Pradesh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 32, Name = "Jammu and Kashmir", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 33, Name = "Jharkhand", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 34, Name = "Karnataka", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 35, Name = "Kerala", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 36, Name = "Ladakh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 37, Name = "Lakshadweep", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 38, Name = "Madhya Pradesh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 39, Name = "Maharashtra", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 40, Name = "Manipur", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 41, Name = "Meghalaya", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 42, Name = "Mizoram", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 43, Name = "Nagaland", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 44, Name = "Odisha", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 45, Name = "Puducherry", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 46, Name = "Punjab", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 47, Name = "Rajasthan", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 48, Name = "Sikkim", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 49, Name = "Tamil Nadu", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 50, Name = "Telangana", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 51, Name = "Tripura", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 52, Name = "Uttar Pradesh", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 53, Name = "Uttarakhand", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 54, Name = "West Bengal", CountryId = 3, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 55, Name = "Aberdeen", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 56, Name = "Aberdeenshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 57, Name = "Angus", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 58, Name = "Antrim", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 59, Name = "Antrim and Newtownabbey", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 60, Name = "Ards", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 61, Name = "Ards and North Down", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 62, Name = "Argyll and Bute", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 63, Name = "Armagh City and District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 64, Name = "Armagh, Banbridge and Craigavon", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 65, Name = "Ascension Island", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 66, Name = "Ballymena Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 67, Name = "Ballymoney", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 68, Name = "Banbridge", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 69, Name = "Barnsley", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 70, Name = "Bath and North East Somerset", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 71, Name = "Bedford", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 72, Name = "Belfast district", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 73, Name = "Birmingham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 74, Name = "Blackburn with Darwen", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 75, Name = "Blackpool", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 76, Name = "Blaenau Gwent County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 77, Name = "Bolton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 78, Name = "Bournemouth", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 79, Name = "Bracknell Forest", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 80, Name = "Bradford", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 81, Name = "Bridgend County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 82, Name = "Brighton and Hove", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 83, Name = "Buckinghamshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 84, Name = "Bury", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 85, Name = "Caerphilly County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 86, Name = "Calderdale", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 87, Name = "Cambridgeshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 88, Name = "Carmarthenshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 89, Name = "Carrickfergus Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 90, Name = "Castlereagh", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 91, Name = "Causeway Coast and Glens", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 92, Name = "Central Bedfordshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 93, Name = "Ceredigion", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 94, Name = "Cheshire East", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 95, Name = "Cheshire West and Chester", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 96, Name = "City and County of Cardiff", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 97, Name = "City and County of Swansea", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 98, Name = "City of Bristol", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 99, Name = "City of Derby", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 100, Name = "City of Kingston upon Hull", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 101, Name = "City of Leicester", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 102, Name = "City of London", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 103, Name = "City of Nottingham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 104, Name = "City of Peterborough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 105, Name = "City of Plymouth", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 106, Name = "City of Portsmouth", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 107, Name = "City of Southampton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 108, Name = "City of Stoke-on-Trent", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 109, Name = "City of Sunderland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 110, Name = "City of Westminster", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 111, Name = "City of Wolverhampton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 112, Name = "City of York", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 113, Name = "Clackmannanshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 114, Name = "Coleraine Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 115, Name = "Conwy County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 116, Name = "Cookstown District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 117, Name = "Cornwall", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 118, Name = "County Durham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 119, Name = "Coventry", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 120, Name = "Craigavon Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 121, Name = "Cumbria", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 122, Name = "Darlington", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 123, Name = "Denbighshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 124, Name = "Derbyshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 125, Name = "Derry City and Strabane", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 126, Name = "Derry City Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 127, Name = "Devon", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 128, Name = "Doncaster", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 129, Name = "Dorset", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 130, Name = "Down District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 131, Name = "Dudley", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 132, Name = "Dumfries and Galloway", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 133, Name = "Dundee", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 134, Name = "Dungannon and South Tyrone Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 135, Name = "East Ayrshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 136, Name = "East Dunbartonshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 137, Name = "East Lothian", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 138, Name = "East Renfrewshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 139, Name = "East Riding of Yorkshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 140, Name = "East Sussex", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 141, Name = "Edinburgh", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 142, Name = "England", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 143, Name = "Essex", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 144, Name = "Falkirk", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 145, Name = "Fermanagh and Omagh", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 146, Name = "Fermanagh District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 147, Name = "Fife", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 148, Name = "Flintshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 149, Name = "Gateshead", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 150, Name = "Glasgow", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 151, Name = "Gloucestershire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 152, Name = "Gwynedd", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 153, Name = "Halton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 154, Name = "Hampshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 155, Name = "Hartlepool", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 156, Name = "Herefordshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 157, Name = "Hertfordshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 158, Name = "Highland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 159, Name = "Inverclyde", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 160, Name = "Isle of Wight", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 161, Name = "Isles of Scilly", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 162, Name = "Kent", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 163, Name = "Kirklees", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 164, Name = "Knowsley", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 165, Name = "Lancashire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 166, Name = "Larne Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 167, Name = "Leeds", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 168, Name = "Leicestershire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 169, Name = "Limavady Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 170, Name = "Lincolnshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 171, Name = "Lisburn and Castlereagh", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 172, Name = "Lisburn City Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 173, Name = "Liverpool", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 174, Name = "London Borough of Barking and Dagenham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 175, Name = "London Borough of Barnet", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 176, Name = "London Borough of Bexley", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 177, Name = "London Borough of Brent", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 178, Name = "London Borough of Bromley", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 179, Name = "London Borough of Camden", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 180, Name = "London Borough of Croydon", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 181, Name = "London Borough of Ealing", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 182, Name = "London Borough of Enfield", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 183, Name = "London Borough of Hackney", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 184, Name = "London Borough of Hammersmith and Fulham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 185, Name = "London Borough of Haringey", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 186, Name = "London Borough of Harrow", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 187, Name = "London Borough of Havering", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 188, Name = "London Borough of Hillingdon", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 189, Name = "London Borough of Hounslow", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 190, Name = "London Borough of Islington", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 191, Name = "London Borough of Lambeth", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 192, Name = "London Borough of Lewisham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 193, Name = "London Borough of Merton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 194, Name = "London Borough of Newham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 195, Name = "London Borough of Redbridge", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 196, Name = "London Borough of Richmond upon Thames", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 197, Name = "London Borough of Southwark", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 198, Name = "London Borough of Sutton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 199, Name = "London Borough of Tower Hamlets", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 200, Name = "London Borough of Waltham Forest", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 201, Name = "London Borough of Wandsworth", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 202, Name = "Magherafelt District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 203, Name = "Manchester", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 204, Name = "Medway", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 205, Name = "Merthyr Tydfil County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 206, Name = "Metropolitan Borough of Wigan", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 207, Name = "Mid and East Antrim", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 208, Name = "Mid Ulster", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 209, Name = "Middlesbrough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 210, Name = "Midlothian", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 211, Name = "Milton Keynes", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 212, Name = "Monmouthshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 213, Name = "Moray", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 214, Name = "Moyle District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 215, Name = "Neath Port Talbot County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 216, Name = "Newcastle upon Tyne", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 217, Name = "Newport", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 218, Name = "Newry and Mourne District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 219, Name = "Newry, Mourne and Down", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 220, Name = "Newtownabbey Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 221, Name = "Norfolk", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 222, Name = "North Ayrshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 223, Name = "North Down Borough Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 224, Name = "North East Lincolnshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 225, Name = "North Lanarkshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 226, Name = "North Lincolnshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 227, Name = "North Somerset", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 228, Name = "North Tyneside", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 229, Name = "North Yorkshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 230, Name = "Northamptonshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 231, Name = "Northern Ireland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 232, Name = "Northumberland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 233, Name = "Nottinghamshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 234, Name = "Oldham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 235, Name = "Omagh District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 236, Name = "Orkney Islands", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 237, Name = "Outer Hebrides", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 238, Name = "Oxfordshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 239, Name = "Pembrokeshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 240, Name = "Perth and Kinross", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 241, Name = "Poole", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 242, Name = "Powys", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 243, Name = "Reading", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 244, Name = "Redcar and Cleveland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 245, Name = "Renfrewshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 246, Name = "Rhondda Cynon Taf", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 247, Name = "Rochdale", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 248, Name = "Rotherham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 249, Name = "Royal Borough of Greenwich", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 250, Name = "Royal Borough of Kensington and Chelsea", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 251, Name = "Royal Borough of Kingston upon Thames", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 252, Name = "Rutland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 253, Name = "Saint Helena", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 254, Name = "Salford", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 255, Name = "Sandwell", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 256, Name = "Scotland", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 257, Name = "Scottish Borders", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 258, Name = "Sefton", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 259, Name = "Sheffield", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 260, Name = "Shetland Islands", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 261, Name = "Shropshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 262, Name = "Slough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 263, Name = "Solihull", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 264, Name = "Somerset", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 265, Name = "South Ayrshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 266, Name = "South Gloucestershire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 267, Name = "South Lanarkshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 268, Name = "South Tyneside", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 269, Name = "Southend-on-Sea", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 270, Name = "St Helens", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 271, Name = "Staffordshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 272, Name = "Stirling", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 273, Name = "Stockport", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 274, Name = "Stockton-on-Tees", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 275, Name = "Strabane District Council", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 276, Name = "Suffolk", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 277, Name = "Surrey", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 278, Name = "Swindon", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 279, Name = "Tameside", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 280, Name = "Telford and Wrekin", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 281, Name = "Thurrock", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 282, Name = "Torbay", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 283, Name = "Torfaen", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 284, Name = "Trafford", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 285, Name = "United Kingdom", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 286, Name = "Vale of Glamorgan", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 287, Name = "Wakefield", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 288, Name = "Wales", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 289, Name = "Walsall", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 290, Name = "Warrington", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 291, Name = "Warwickshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 292, Name = "West Berkshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 293, Name = "West Dunbartonshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 294, Name = "West Lothian", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 295, Name = "West Sussex", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 296, Name = "Wiltshire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 297, Name = "Windsor and Maidenhead", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 298, Name = "Wirral", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 299, Name = "Wokingham", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 300, Name = "Worcestershire", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 301, Name = "Wrexham County Borough", CountryId = 4, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 302, Name = "Alabama", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 303, Name = "Alaska", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 304, Name = "American Samoa", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 305, Name = "Arizona", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 306, Name = "Arkansas", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 307, Name = "Baker Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 308, Name = "California", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 309, Name = "Colorado", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 310, Name = "Connecticut", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 311, Name = "Delaware", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 312, Name = "District of Columbia", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 313, Name = "Florida", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 314, Name = "Georgia", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 315, Name = "Guam", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 316, Name = "Hawaii", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 317, Name = "Howland Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 318, Name = "Idaho", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 319, Name = "Illinois", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 320, Name = "Indiana", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 321, Name = "Iowa", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 322, Name = "Jarvis Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 323, Name = "Johnston Atoll", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 324, Name = "Kansas", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 325, Name = "Kentucky", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 326, Name = "Kingman Reef", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 327, Name = "Louisiana", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 328, Name = "Maine", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 329, Name = "Maryland", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 330, Name = "Massachusetts", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 331, Name = "Michigan", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 332, Name = "Midway Atoll", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 333, Name = "Minnesota", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 334, Name = "Mississippi", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 335, Name = "Missouri", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 336, Name = "Montana", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 337, Name = "Navassa Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 338, Name = "Nebraska", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 339, Name = "Nevada", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 340, Name = "New Hampshire", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 341, Name = "New Jersey", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 342, Name = "New Mexico", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 343, Name = "New York", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 344, Name = "North Carolina", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 345, Name = "North Dakota", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 346, Name = "Northern Mariana Islands", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 347, Name = "Ohio", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 348, Name = "Oklahoma", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 349, Name = "Oregon", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 350, Name = "Palmyra Atoll", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 351, Name = "Pennsylvania", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 352, Name = "Puerto Rico", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 353, Name = "Rhode Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 354, Name = "South Carolina", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 355, Name = "South Dakota", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 356, Name = "Tennessee", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 357, Name = "Texas", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 358, Name = "United States Minor Outlying Islands", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 359, Name = "United States Virgin Islands", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 360, Name = "Utah", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 361, Name = "Vermont", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 362, Name = "Virginia", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 363, Name = "Wake Island", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 364, Name = "Washington", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 365, Name = "West Virginia", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 366, Name = "Wisconsin", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now },
new State { Id = 367, Name = "Wyoming", CountryId = 5, CreatedOn = DateTime.Now, ModifiedOn = DateTime.Now }

                );
        }
    }
}

